@startuml
rectangle "AddressReference" as AddressReference
rectangle "Authorization" as Authorization
rectangle "Code" as Code
rectangle "CommunicationChannel" as CommunicationChannel
rectangle "ContactMethod" as ContactMethod
rectangle "ControlAccountReference" as ControlAccountReference
rectangle "CurrencyExchange" as CurrencyExchange
rectangle "DepartmentReference" as DepartmentReference
rectangle "Discount" as Discount
rectangle "DiscountMetricValue" as DiscountMetricValue
rectangle "DiscountPolicy" as DiscountPolicy
rectangle "EffectivePeriod" as EffectivePeriod
rectangle "Garage" as Garage
rectangle "GarageItem" as GarageItem
rectangle "Identifier" as Identifier
rectangle "Locale" as Locale
rectangle "MetricNameValue" as MetricNameValue
rectangle "MetricValue" as MetricValue
rectangle "Money" as Money
rectangle "OrgName" as OrgName
rectangle "OrgProfile" as OrgProfile
rectangle "Party" as Party
rectangle "PartyReference" as PartyReference
rectangle "PaymentMethodReference" as PaymentMethodReference
rectangle "PaymentTermReference" as PaymentTermReference
rectangle "PayrollRate" as PayrollRate
rectangle "Person" as Person
rectangle "PersonName" as PersonName
rectangle "PersonReference" as PersonReference
rectangle "Price" as Price
rectangle "PrivacyEvent" as PrivacyEvent
rectangle "PrivacyItem" as PrivacyItem
rectangle "ProductModel" as ProductModel
rectangle "StaffAffinity" as StaffAffinity
rectangle "StaffCertification" as StaffCertification
rectangle "StaffMember" as StaffMember
rectangle "StaffSkill" as StaffSkill
rectangle "Team" as Team
rectangle "TextualDetail" as TextualDetail
rectangle "TimeSlot" as TimeSlot
rectangle "VehicleIdentifier" as VehicleIdentifier
rectangle "VehicleLicense" as VehicleLicense
rectangle "AddressTypes" as AddressTypes #FAFF91
rectangle "BusinessTypes" as BusinessTypes #FAFF91
rectangle "CommunicationChannelTypes" as CommunicationChannelTypes #FAFF91
rectangle "DaysOfWeekTypes" as DaysOfWeekTypes #FAFF91
rectangle "DepartmentTypes" as DepartmentTypes #FAFF91
rectangle "DiscountTypes" as DiscountTypes #FAFF91
rectangle "DueOnTypes" as DueOnTypes #FAFF91
rectangle "DurationUOMTypes" as DurationUOMTypes #FAFF91
rectangle "GenderTypes" as GenderTypes #FAFF91
rectangle "MaritalStatusTypes" as MaritalStatusTypes #FAFF91
rectangle "NarrativeUomTypes" as NarrativeUomTypes #FAFF91
rectangle "OperatingStatusTypes" as OperatingStatusTypes #FAFF91
rectangle "OrderCategoryTypes" as OrderCategoryTypes #FAFF91
rectangle "PartIdentifierTypes" as PartIdentifierTypes #FAFF91
rectangle "PartyRelationshipTypes" as PartyRelationshipTypes #FAFF91
rectangle "PartyServiceTypes" as PartyServiceTypes #FAFF91
rectangle "PartyTypes" as PartyTypes #FAFF91
rectangle "PayTypes" as PayTypes #FAFF91
rectangle "PaymentMethodTypes" as PaymentMethodTypes #FAFF91
rectangle "PaymentTypes" as PaymentTypes #FAFF91
rectangle "PayrollCycleFrequencyTypes" as PayrollCycleFrequencyTypes #FAFF91
rectangle "PriceTypes" as PriceTypes #FAFF91
rectangle "PrivacyContextTypes" as PrivacyContextTypes #FAFF91
rectangle "PrivacyLegalBasisTypes" as PrivacyLegalBasisTypes #FAFF91
rectangle "PrivacyStateTypes" as PrivacyStateTypes #FAFF91
rectangle "PrivacyTypes" as PrivacyTypes #FAFF91
rectangle "ProductStateTypes" as ProductStateTypes #FAFF91
rectangle "ProductViewTypes" as ProductViewTypes #FAFF91
rectangle "RoleTypes" as RoleTypes #FAFF91
rectangle "SkillCategoryTypes" as SkillCategoryTypes #FAFF91
rectangle "StaffPayTypes" as StaffPayTypes #FAFF91
rectangle "TimeslotDirectiveTypes" as TimeslotDirectiveTypes #FAFF91
rectangle "UnitOfMeasureTypes" as UnitOfMeasureTypes #FAFF91
rectangle "ValidationTypes" as ValidationTypes #FAFF91
AddressReference *-- PartyReference
AddressTypes *-- AddressReference
Authorization *-- CommunicationChannel
BusinessTypes -- OrgProfile
Code *-- ControlAccountReference
Code *-- DepartmentReference
Code *-- Discount
Code *-- DiscountMetricValue
Code *-- EffectivePeriod
Code *-- GarageItem
Code *-- Identifier
Code *-- MetricNameValue
Code *-- MetricValue
Code *-- OrgProfile
Code *-- PersonReference
Code *-- ProductModel
Code *-- StaffAffinity
Code *-- StaffMember
Code *-- TextualDetail
Code *-- VehicleIdentifier
CommunicationChannelTypes -- CommunicationChannel
CommunicationChannel *-- ContactMethod
CommunicationChannel *-- PartyReference
CommunicationChannel *-- Person
CommunicationChannel *-- StaffMember
ContactMethod *-- Party
ControlAccountReference -- Discount
ControlAccountReference *-- OrgProfile
CurrencyExchange -- Money
CurrencyExchange -- Price
DaysOfWeekTypes -- TimeSlot
DepartmentReference -- StaffMember
DepartmentReference -- Team
DepartmentTypes -- DepartmentReference
DiscountMetricValue *-- Discount
DiscountTypes *-- Discount
Discount *-- DiscountPolicy
DueOnTypes -- Discount
DurationUOMTypes -- EffectivePeriod
EffectivePeriod -- DepartmentReference
EffectivePeriod -- Discount
EffectivePeriod -- GarageItem
EffectivePeriod -- PayrollRate
EffectivePeriod -- Price
EffectivePeriod -- TimeSlot
EffectivePeriod -- VehicleLicense
Garage -- Party
GarageItem *-- Garage
GenderTypes -- Person
Identifier -- ControlAccountReference
Identifier -- DepartmentReference
Identifier -- PartyReference
Identifier -- PaymentTermReference
Identifier -- PersonReference
Identifier *-- Discount
Identifier *-- Garage
Identifier *-- OrgProfile
Identifier *-- Party
Identifier *-- PaymentMethodReference
Identifier *-- Person
Identifier *-- PrivacyItem
Identifier *-- ProductModel
Identifier *-- StaffAffinity
Identifier *-- StaffMember
Identifier *-- TextualDetail
Identifier *-- VehicleIdentifier
Locale -- CommunicationChannel
MaritalStatusTypes -- Person
MetricNameValue *-- Person
MetricValue -- VehicleIdentifier
Money -- PayrollRate
NarrativeUomTypes -- MetricNameValue
NarrativeUomTypes -- MetricValue
OperatingStatusTypes -- OrgProfile
OrderCategoryTypes *-- Discount
OrgName -- OrgProfile
OrgProfile *-- Party
PartIdentifierTypes *-- OrgProfile
PartyReference *-- PayrollRate
PartyReference *-- StaffMember
PartyReference *-- Team
PartyRelationshipTypes *-- PartyReference
PartyRelationshipTypes -- PersonReference
PartyServiceTypes *-- Party
PartyTypes *-- Party
PartyTypes *-- Person
PayTypes -- Price
PaymentMethodReference *-- OrgProfile
PaymentMethodTypes -- PaymentMethodReference
PaymentTermReference *-- OrgProfile
PaymentTypes *-- Discount
PayrollCycleFrequencyTypes -- PayrollRate
PayrollRate *-- StaffMember
PersonName -- PartyReference
PersonName -- Person
PersonReference -- StaffMember
Person *-- Party
Price -- Discount
PriceTypes *-- Price
PrivacyContextTypes -- PrivacyEvent
PrivacyEvent *-- PrivacyItem
PrivacyItem *-- Person
PrivacyItem *-- StaffMember
PrivacyLegalBasisTypes -- PrivacyEvent
PrivacyStateTypes -- PrivacyEvent
PrivacyTypes -- PrivacyItem
ProductModel -- VehicleIdentifier
ProductStateTypes *-- Discount
ProductViewTypes -- Discount
RoleTypes *-- StaffMember
SkillCategoryTypes -- StaffSkill
StaffMember *-- OrgProfile
StaffAffinity -- StaffMember
StaffCertification *-- StaffMember
StaffPayTypes -- PayrollRate
StaffSkill *-- StaffMember
Team *-- StaffMember
TextualDetail *-- Discount
TextualDetail *-- PayrollRate
TimeSlot -- EffectivePeriod
TimeSlot *-- StaffAffinity
TimeslotDirectiveTypes *-- TimeSlot
UnitOfMeasureTypes -- DiscountMetricValue
ValidationTypes -- Discount
VehicleIdentifier -- GarageItem
VehicleLicense -- VehicleIdentifier
@enduml
