@startuml
class AddressReference {
addressReferenceKey:String
addressReferenceValue:String
addressTypes:List<AddressTypes>
addressLine1:String
addressLine2:String
addressLine3:String
addressLine4:String
addressLine5:String
city:String
countryCode:String
district:String
label:String
postalCode:String
stateProvince:String
}
class Authorization {
updateDateTime:Date
authorizedIndicator:Boolean
authorizationKey:String
}
class Code {
codeId:String
codeKey:String
code:String
description:String
}
class CommunicationChannel {
communicationChannelKey:String
communicationChannelId:String
communicationChannelType:CommunicationChannelTypes
value:String
valueExtension:String
label:String
locale:Locale
preferredIndicator:Boolean
preferences:List<TimeSlot>
authorizations:List<Authorization>
}
class ContactMethod {
contactMethodId:String
contactMethodKey:String
communicationChannels:List<CommunicationChannel>
}
class ControlAccountReference {
controlAccountReferenceId:String
controlAccountReferenceKey:String
controlAccountKey:String
context:String
systemCodes:List<Code>
controlAccount:Identifier
occurrenceDateTime:Date
}
class CurrencyExchange {
currencyExchangeId:String
currencyExchangeKey:String
sourceCurrency:String
targetCurrency:String
currencyExchangeDesc:String
exchangeRate:String
rateDateTime:Date
}
class DepartmentReference {
departmentReferenceId:String
departmentReferenceKey:String
departmentKey:String
departmentType:DepartmentTypes
context:String
systemCodes:List<Code>
department:Identifier
occurrenceDateTime:Date
duration:EffectivePeriod
}
class Discount {
discountId:String
discountKey:String
discountPlanName:String
capitalizedIndicator:Boolean
taxableIndicator:Boolean
controlAccountReference:ControlAccountReference
discountCodes:List<Code>
promoCodes:List<Code>
discountDuration:EffectivePeriod
discountHref:String
discountPercentValue:String
discountPrice:Price
discountTypes:List<DiscountTypes>
dueOnType:DueOnTypes
identifiers:List<Identifier>
locationCodes:List<Code>
paymentTypes:List<PaymentTypes>
purchaseTypes:List<OrderCategoryTypes>
taxabilityIndicator:Boolean
validationType:ValidationTypes
productStateTypes:List<ProductStateTypes>
textualDetails:List<TextualDetail>
productViewType:ProductViewTypes
discountMetricValues:List<DiscountMetricValue>
sequenceId:String
}
class DiscountMetricValue {
uom:UnitOfMeasureTypes
value:String
locales:List<Code>
metricValueKey:String
}
class DiscountPolicy {
policyKey:String
policyId:String
policyName:String
discounts:List<Discount>
effectiveStartDate:Date
effectiveEndDate:Date
}
class EffectivePeriod {
effectivePeriodKey:String
activeIndicator:Boolean
exclusiveIndicator:Boolean
startDateTime:Date
completeDateTime:Date
durationUomType:DurationUOMTypes
durationValue:String
recurUomType:DurationUOMTypes
recurCount:String
recurValues:List<Code>
recurCriteria:String
recurIndicator:Boolean
timeslot:TimeSlot
}
class Garage {
garageId:String
garageKey:String
identifiers:List<Identifier>
garageItems:List<GarageItem>
}
class GarageItem {
garageItemId:String
garageItemKey:String
vehicleIdentifier:VehicleIdentifier
primaryDriverIndicator:Boolean
ownershipDates:EffectivePeriod
owners:List<Code>
drivers:List<Code>
}
class Identifier {
identifierId:String
identifierKey:String
context:String
value:String
detail:String
identifierType:String
systemCodes:List<Code>
}
class Locale {
localeKey:String
localeName:String
description:String
languageCode:String
countryCode:String
currencyCode:String
currencySymbol:String
timezone:String
numberFormat:String
locationCode:String
}
class MetricNameValue {
metricNameValueKey:String
metricNameValueId:String
headerSequence:String
uom:NarrativeUomTypes
value:String
valueCategory:String
valueDescription:String
valueName:String
codes:List<Code>
}
class MetricValue {
metricValueId:String
metricValueKey:String
value:String
uom:NarrativeUomTypes
codes:List<Code>
}
class Money {
moneyKey:String
moneyId:String
currencyCode:String
displayValue:String
locale:String
value:String
currencyExchange:CurrencyExchange
}
class OrgName {
orgNameKey:String
alias:String
identifiersHref:String
orgNameId:String
organizationContact:String
organizationName:String
partyKey:String
preferredName:String
}
class OrgProfile {
orgProfileKey:String
orgProfileId:String
alias:String
annualRevenue:String
businessType:BusinessTypes
currency:String
dateEstablished:String
dba:List<Code>
domesticDuns:List<Code>
employeeCount:String
globalDuns:String
legalStatus:String
locale:String
nationalTaxIdentifier:String
taxExemptIndicator:Boolean
legalNameForTaxPurposes:String
w9OnFileIndicator:Boolean
Reportable1099Indicator:Boolean
paymentMethodReferences:List<PaymentMethodReference>
standardPaymentTerms:List<PaymentTermReference>
standardDiscountPolicies:List<DiscountPolicy>
controlAccounts:List<ControlAccountReference>
operatingStatusType:OperatingStatusTypes
orgContactMethod:String
orgName:OrgName
inceptionDate:Date
parentDuns:String
parentOrgId:String
orgContactName:String
partIdentifierTypes:List<PartIdentifierTypes>
identifiers:List<Identifier>
staff:List<StaffMember>
}
class Party {
alias:String
comments:String
contactMethods:List<ContactMethod>
contactMethodsHref:String
countryCode:String
fullName:String
identifiers:List<Identifier>
identifiersHref:String
orgIndicator:Boolean
orgProfilesHref:String
partyKey:String
partyTypes:List<PartyTypes>
preferredLanguageCode:String
preferredName:String
privaciesHref:String
specialRemarksDescription:String
partyId:String
persons:List<Person>
orgProfiles:List<OrgProfile>
partyServiceTypes:List<PartyServiceTypes>
garage:Garage
}
class PartyReference {
partyReferenceId:String
partyReferenceKey:String
partyKey:String
partyName:String
contactName:PersonName
authorizationCode:String
sourceSystemCode:String
context:String
accountNumber:String
partyRelationshipTypes:List<PartyRelationshipTypes>
snapshot_detail:Identifier
addressReferences:List<AddressReference>
communicationChannels:List<CommunicationChannel>
occurrenceDateTime:Date
}
class PaymentMethodReference {
paymentMethodReferenceId:String
paymentMethodReferenceKey:String
paymentMethodKey:String
context:String
paymentMethodType:PaymentMethodTypes
processorOptions:List<Identifier>
snapshotDetails:List<Identifier>
occurrenceDateTime:Date
}
class PaymentTermReference {
termReferenceId:String
termReferenceKey:String
termKey:String
context:String
identifier:Identifier
occurrenceDateTime:Date
}
class PayrollRate {
payrollRateId:String
payrollRateKey:String
staffMemberKey:String
partyReferences:List<PartyReference>
payrollCycleType:PayrollCycleFrequencyTypes
amount:Money
effectivePeriod:EffectivePeriod
occurrenceDateTime:Date
textualDetails:List<TextualDetail>
staffPayType:StaffPayTypes
}
class Person {
personId:String
personKey:String
age:Integer
birthDate:Date
comments:String
communicationChannels:List<CommunicationChannel>
countryCode:String
genderType:GenderTypes
birthCountry:String
citizenshipCountry:String
identifiers:List<Identifier>
identifiersHref:String
maritalStatusType:MaritalStatusTypes
orgProfilesHref:String
partyKey:String
partyTypes:List<PartyTypes>
personAttributes:List<MetricNameValue>
preferredLanguageCode:String
privacies:List<PrivacyItem>
privaciesHref:String
specialRemarksDescription:String
personName:PersonName
}
class PersonName {
alias:String
familyName:String
fullName:String
givenName:String
identifiersHref:String
maidenName:String
middleName:String
nameSuffix:String
partyKey:String
personKey:String
personNameKey:String
preferredName:String
salutation:String
honorificPrefix:String
honorificSuffix:String
locale:String
phoneticFamilyName:String
phoneticGivenName:String
phoneticMiddleName:String
nationality:String
}
class PersonReference {
personReferenceId:String
personReferenceKey:String
personKey:String
partyKey:String
relationshipType:PartyRelationshipTypes
context:String
fullname:String
systemCodes:List<Code>
identifier:Identifier
occurrenceDateTime:Date
}
class Price {
displayValue:String
locale:String
value:String
taxValue:String
taxableAmount:String
nonTaxableAmount:String
totalAmount:String
totalCostAmount:String
unitCostAmount:String
priceDescription:String
priceKey:String
taxIncludedIndicator:Boolean
currencyCode:String
priceId:String
duration:EffectivePeriod
priceTypes:List<PriceTypes>
payType:PayTypes
currencyExchange:CurrencyExchange
}
class PrivacyEvent {
privacyEventId:String
privacyEventKey:String
legalBasisType:PrivacyLegalBasisTypes
privacyContextType:PrivacyContextTypes
privacyStateType:PrivacyStateTypes
value:String
eventReference:String
occurrenceDateTime:Date
}
class PrivacyItem {
privacyId:String
privacyKey:String
privacyEvent:List<PrivacyEvent>
privacyType:PrivacyTypes
encryptedValue:String
hashValue:String
identifiers:List<Identifier>
lastUpdatedDateTime:Date
}
class ProductModel {
productModelKey:String
productModelId:String
identifiers:List<Identifier>
brands:List<Code>
trims:List<Code>
marketingNames:List<Code>
oemNames:List<Code>
oemCodes:List<Code>
modelCodes:List<Code>
phaseCode:String
nicknames:List<Code>
tags:List<Code>
}
class StaffAffinity {
staffAffinityId:String
staffAffinityKey:String
staffMemberKey:String
partyKey:String
status:String
communicationStyles:List<Code>
productAffinities:List<Code>
languagesSpoken:List<Code>
yearsInIndustry:String
staffPerformanceMetrics:List<Identifier>
lastAssignmentAt:Date
leadScoreThreshold:String
isEligibleForAssignment:Boolean
availablity:List<TimeSlot>
unavailablity:List<TimeSlot>
}
class StaffCertification {
staffCertificationId:String
staffCertificationKey:String
certificationName:String
issuingBody:String
certificationNumber:String
status:String
}
class StaffMember {
staffMemberId:String
staffMemberKey:String
employeeKey:String
partyKey:String
personReference:PersonReference
skills:List<StaffSkill>
specialties:List<Code>
certifications:List<StaffCertification>
email:String
stateLicenseNumber:String
activeIndicator:Boolean
jobTitle:String
departmentName:String
departmentReference:DepartmentReference
teamId:List<Team>
communicationChannels:List<CommunicationChannel>
contactMethodsHref:String
comments:String
roleTypes:List<RoleTypes>
identifiers:List<Identifier>
profileHref:String
partyReferences:List<PartyReference>
payrollRates:List<PayrollRate>
privacyItems:List<PrivacyItem>
staffAffinity:StaffAffinity
teams:List<Team>
}
class StaffSkill {
staffSkillId:String
staffSkillKey:String
staffSkillCode:String
staffSkillName:String
staffSkillDescription:String
proficiencyLevel:String
skillCategoryType:SkillCategoryTypes
yearsExperience:String
}
class Team {
teamKey:String
teamId:String
teamName:String
departmentKey:String
department:DepartmentReference
members:List<PartyReference>
}
class TextualDetail {
textualDetailKey:String
textualDetailId:String
localeCodes:List<Code>
shortDescription:String
textKey:String
name:String
value:String
identifiers:List<Identifier>
groups:List<Code>
label:String
altText:String
textualDetailCode:String
tags:List<Code>
uomDisplay:String
uomCode:String
}
class TimeSlot {
timeSlotId:String
timeSlotKey:String
timeSlotSource:String
startDay:DaysOfWeekTypes
startTime:String
endDay:DaysOfWeekTypes
endTime:String
recurringIndicator:Boolean
recurringPeriod:EffectivePeriod
timeslotDirectiveTypes:List<TimeslotDirectiveTypes>
}
class VehicleIdentifier {
vehicleIdentifierKey:String
vehicleIdentifierId:String
odometer:MetricValue
vehicleKey:String
unitId:String
stockNumber:String
identifiers:List<Identifier>
license:VehicleLicense
make:String
model:String
brand:String
trim:String
oemModelCode:String
oemName:String
oemCode:String
modelCode:String
modelDescription:String
modelYear:String
vin:String
tags:List<Code>
modelDetail:ProductModel
}
class VehicleLicense {
vehicleLicenseKey:String
plateNumber:String
jurisdictionName:String
countryCode:String
effectivePeriod:EffectivePeriod
}
class AddressTypes #FAFF91 {
ARCHIVE
AR_ADDRESS
BILLING
BUSINESS
CONTRACT
CURRENT
DEALER
DELIVERY
DESTINATION
EMERGENCY
GARAGE
HOME
INSURANCE
LEGAL
MAILING
OFFICE
ORIGINAL
OTHER
POSTAL
PO_BOX
PREVIOUS
PRODUCT
REBATE
RECIPIENT
RESIDENCE
SERVICE
SERVICE_CONTRACT
SHIPPING
TEMPORARY
VACATION
WORK
}
class BusinessTypes #FAFF91 {
AGENT
CORPORATION
INDIVIDUAL
OTHER
PARTNERSHIP
}
class CommunicationChannelTypes #FAFF91 {
APP
BROADCAST
CELL
DIRECT_MAIL
EMAIL
OTHER
PDA
PHONE
SMS
SOCIAL_MEDIA
URL
VIDEO
VOICE
}
class DaysOfWeekTypes #FAFF91 {
FRI
MON
SAT
SUN
THURS
TUES
WED
}
class DepartmentTypes #FAFF91 {
ACCESSORY_INSTALL
BODY_SHOP
FIELD_ACTION
FLEET
F_I
PDI_INSPECTION
QUICK_LUBE
REGULAR_INSPECTION
SALES
SERVICE
USED_VEHICLES
}
class DiscountTypes #FAFF91 {
ACCESSORY
ADD_ON
AMOUNT
BONUS_CASH
BULK
CASH
CASH_BACK_REBATES
COMPETITOR
COUPON
CREDIT_UNION
EDUCATOR
EMPLOYER
FEE
FINANCE
FLAT_RATE
INSTALLATION
LEASE
LOYALTY
MILITARY
NEGOTIATE
OEM
OEM_CLUBS
OPTION
ORGANIZATION
OTHER
PACKAGE
PAY_UPFRONT
PERCENTAGE
REWARDS
SALES
SERVICE
STUDENT
TRADE
}
class DueOnTypes #FAFF91 {
CLOSE
CUT_OFF
DAY_OF_MONTH
DELIVERY
HOLD
IMMEDIATE
INCEPTION
NONE
OTHER
PROMPT
RECUR
SALE
SCHEDULE
SIGNING
TRIAL_COMPLETE
TRIAL_START
}
class DurationUOMTypes #FAFF91 {
BI_WEEKS
CUSTOM
DAYS
DAY_OF_MONTH
HOURS
MINUTES
MONTHS
MULTI_YEARS
NONE
OCCURRENCE
OTHER
QUARTERS
SEMI_MONTHS
SEMI_YEARS
UNLIMITED
WEEKS
YEARS
}
class GenderTypes #FAFF91 {
FEMALE
MALE
NA
TRANS_FEMALE
TRANS_MALE
UNKNOWN
}
class MaritalStatusTypes #FAFF91 {
ANNULLED
COMMON_LAW
DIVORCED
MARRIED
OTHER
SEPARATED
SINGLE
UNKNOWN
WIDOWED
}
class NarrativeUomTypes #FAFF91 {
AMPERE
ARRAY
BAR
BINARY
BI_WEEKS
BOOLEAN
CELSIUS
CENTIMETER
CODE
CUBIC_METER
CURRENCY
CUSTOM
DATE
DATE_TIME
DAYS
DAY_OF_MONTH
DEGREES
DESC
DOUBLE
DURATION
FAHRENHEIT
FATHOM
FEET
FLOAT
FLUID_OUNCE
GALLON
GRAMS
GROUP
G_FORCE
HOURS
HP
INCH
INT32
INT64
INTEGER
KELVIN
KEY
KG
KILOWATT_HOUR
KM
KPA
LABEL
LB
LITER
METER
MI
MILES
MILLIMETER
MINUTES
MONTHS
MULTI_YEARS
NAUTICAL
NONE
NUMBER
OBJECT
OCCURRENCE
OHM
OTHER
OZ
PERCENT
POINTS
PROTECTED_TEXT
PSI
QUARTERS
RANKINE
RPM
SECONDS
SEMI_MONTHS
SEMI_YEARS
STRING
TEXT
TIME
TONS
UNLIMITED
VOLT
WATT
WEEKS
YARD
YEARS
}
class OperatingStatusTypes #FAFF91 {
ACTIVE
ARCHIVED
BETA
CLOSED
DECOMMISSIONED
DORMANT
DRAFT
ERROR
FAILURE
HOLD
INACTIVE
ONLINE
OPERATIONAL
OTHER
PENDING
PROPOSED
SUSPENDED
TERMINATED
TRIAL
UNDER_REVIEW
UNKNOWN
}
class OrderCategoryTypes #FAFF91 {
COMMERCIAL
CONTRACT
CUSTOM_ORDER
DIRECT
EDUCATIONAL
E_COMMERCE
FLEET
GOVERNMENT
LEASE
OTHER
RETAIL
STANDARD
SUBSCRIPTION
TRADE_IN
WHOLESALE
}
class PartIdentifierTypes #FAFF91 {
ALT_CODE
CATALOG_CODE
CONFIG_CODE
COUNTRY_OF_ORIGIN_CODE
DRAWING_NUMBER
ENGINE_CODE
ISBN
MAKE_CODE
MARKET_DIVISION_CODE
MFR_CODE
MODEL_CODE
MPN
NAME
NUMBER
OTHER
PREFIX
PRODUCT_CODE
SKU
STOCK_NBR
STYLE_CODE
SUB_MODEL_CODE
TRANSMISSION_CODE
TRIM_CODE
UNIV_CODE
UPCA
UPCE
VIN
YEAR_CODE
}
class PartyRelationshipTypes #FAFF91 {
ACCOUNTABLE
ACQUAINTANCE
ACTOR
ADVISOR
ADVISOR_CONSULTANT
AFFILIATE
AGENT
APPLICANT
ASSOCIATE
AUDITOR
BENEFICIARY
BRANCH
BUSINESS_DEVELOPMENT
BUSINESS_PARTNER
BUYER
CAREGIVER
CHILD
CLOSING_MGR
COMPOSED_IN
CONCIERGE_MGR
CONCIERGE_STAFF
CONSULT
CONTRACTOR
CORPORATION
COST_CENTER
CO_APPLICANT
CO_SIGNER
CO_WORKER
CREDIT_CARD_PROVIDER
CUSTODIAN
CUSTOMER
DEALERSHIP
DEPARTMENT
DEPENDENT
DISTRIBUTOR
DIVISION
DRIVER
EMERGENCY_CONTACT
EMPLOYEE
EMPLOYER
EXECUTE
EX_SPOUSE
FAMILY_MEMBER
FINANCE
FINANCIAL_ADVISOR
FI_MGR
FRANCHISE
FREIGHT_FORWARDER
FRIEND
GEN_MGR
GIFT_TO
GOVERNMENT_AGENCY
GROUP
GUARANTOR
HEIR
INSURED
INSURER
INTERNAL_ORGANIZATION
INVESTOR
JOINT_VENTURE
LEGAL_GUARDIAN
LESSEE
LESSOR
LIEN_HOLDER
LOAN_PROVIDER
MANAGER
MANUFACTURER
MEMBERSHIP
MENTEE
MENTOR
MERCHANT
NON_PROFIT
NOTIFY
OEM
OTHER
OTHER_FAMILY
OWNER
PARENT
PARTNER_ORGANIZATION
PART_OF
PASSENGER
PAYEE
PAYER
POLITICAL_AFFILIATE
PRIMARY_OEM
PROFESSIONAL_CONTACT
PROVIDER
PROXY
RECIPIENT
REFERENCE_PERSONAL
REFERENCE_PROFESSIONAL
REGULATOR
REMOVE
RESPONSIBLE
ROMANTIC_PARTNER
SALES_ASSOC
SALES_MGR
SECTION
SELF
SERVICE_CONSUMER
SERVICE_MGR
SERVICE_PROVIDER
SERVICE_TECH
SHAREHOLDER
SHIP_TO
SIBLING
SOLD_TO
SPECIALIST
SPOUSE
STAFF
STORE
SUBSIDIARY
SUPPLIER
TEAM
THIRD_PARTY
TRANSACTION_FROM
TRANSACTION_TO
TRUSTEE_PERSON
UNDERWRITER
VALET
VENDOR
}
class PartyServiceTypes #FAFF91 {
BODY_SHOP_VENDOR
CRM_VENDOR
DMS_VENDOR
FEE_VENDOR
FINANCE_VENDOR
FLEET_SERVICES
INSURANCE_VENDOR
IT_VENDOR
MARKETING_VENDOR
PARTS_VENDOR
PRODUCT_VENDOR
REBATE_VENDOR
REPAIR_VENDOR
SERVICE_CONTRACT_VENDOR
TAX_VENDOR
TIRE_VENDOR
TITLE_AND_REGISTRATION_VENDOR
UNKNOWN
WEBSITE_VENDOR
}
class PartyTypes #FAFF91 {
CONTRACTOR
CUSTOMER
DEALER
DEVICE
DRIVER
EMPLOYEE
FINANCE
FLEET
GOVERNMENT
GROUP
ORGANIZATION
PARTNER
PERSON
PROSPECT
PUBLIC
RENTAL
RESALE
SERVICE
SUPPLIER
TAX
VENDOR
}
class PayTypes #FAFF91 {
CUSTOMER_PAY
DEALER
INTERNAL
MANUFACTURER
SUBLET
WARRANTY
}
class PaymentMethodTypes #FAFF91 {
CASH
CASH_ON_DELIVERY
CHECK
CREDIT_CARD
CRYPTOCURRENCY
DEBIT_CARD
DUE_ON_RECEIPT
EFT
EXCHANGE
FINANCE
GIFT_CARD
LEASE
MOBILE_WALLET
MONEY_ORDER
NOT_APPLICABLE
ONLINE_BANK_TRANSFER
ONLINE_PAYMENT_PLATFORM
OTHER
PAYROLL_DEDUCTION
RENTAL
REWARD_POINTS
STORE_CREDIT
TERMS
TRADE_IN
}
class PaymentTypes #FAFF91 {
BALLON
CASH
CONSUMPTION_BASED
CUSTOM_AGREEMENT
DEPOSIT
FINANCED_PURCHASE
LEASE
LEASE_BUYOUT
LEASE_NO_BUYOUT
OUTRIGHT_PURCHASE
PROGRESS_PAYMENT
SCHEDULED_PAYMENT
SUBSCRIPTION
}
class PayrollCycleFrequencyTypes #FAFF91 {
ANNUAL
BI_MONTHLY
BI_WEEKLY
DAILY
MONTHLY
OFF_CYCLE
ON_DEMAND
QUARTERLY
SEMI_ANNUAL
SEMI_MONTHLY
WEEKLY
}
class PriceTypes #FAFF91 {
ACTUAL
ADJUSTED_MSRP
AFFILIATE
APPLIED_REWARD_TOTAL
BALANCE
BASE
BASE_MSRP
BUNDLE
CONTRACT
CORE
CREDIT_TOTAL
CUSTOM
CUSTOMER
DEALER_COST
DISABILITY_PREMIUM_TOTAL
DISCOUNT
DISCOUNT_PACKAGES_TOTAL
DISCOUNT_TOTAL
ESTIMATED
FEE_TOTAL
FINANCE_TOTAL
FLAT
FREIGHT_CHARGE
FUEL
GROSS_SALE
INTERNET
ITEMIZED
LANDED
LICENSED
LIST
LOCATION
METERED
MONEY
MSRP
NET
NET_SALE
NET_SALE_REDUCTION_PRICE
NONTAXABLE
ONLINE
OTHER
PERCENT
PER_UNIT
PPO_HOLD_BACK
PREMIUM_TOTAL
PRODUCT_TOTAL
PROMOTIONAL
PURCHASE
QUANTITY
REBATE_TOTAL
RECONDITIONING_COST
REGION
REMOVED_EQUIPT_TOTAL
RESIDUAL_VALUE
RETAIL
SALE
SEAT
STAIR_STEP
STANDARD
STORE
SUBSCRIPTION
TAX
TAXABLE
TAX_TOTAL
TDA
TIER_GRADUATED
TIER_VOLUME
TOTAL
TOTAL_COST
TOTAL_DEALER_COST
TOTAL_DEALER_OPTION_COST
TOTAL_DEALER_OPTION_SELLING_PRICE
TOTAL_HOLD_BACK
TOTAL_MSRP
TOTAL_OPTION_MSRP
TRADE
TRADE_IN_EQUITY_TOTAL
TRADE_IN_TOTAL
UNIT
UNIT_COST
UPFRONT_PAYMENT_TOTAL
USAGE
VOLUME
WHOLESALE
WRF
}
class PrivacyContextTypes #FAFF91 {
ACCESS_DATA
DATA_PORTABILITY
ERASURE_OF_DATA
GET_BREACH_NOTIFICATION
GIVE_CONSENT
INFORMED_OF_COLLECTION
OBJECT_TO_PROCESSING
OTHER
RECTIFICATION_OF_DATA
RESTRICT_PROCESSING
}
class PrivacyLegalBasisTypes #FAFF91 {
CONSENT
CONTRACT
LEGAL_OBLIGATION
LEGITIMATE_INTERESTS
PUBLIC_TASK
UNKNOWN
VITAL_INTERESTS
}
class PrivacyStateTypes #FAFF91 {
ACTIVE_REVIEW
GIVEN
IN_COMPLIANCE
NOT_APPLICABLE
OTHER
OUT_OF_COMPLIANCE
PENDING
PENDING_RESOLUTION
RESOLVED
REVOKED
}
class PrivacyTypes #FAFF91 {
BANK_ACCOUNT_NUMBER
CREDIT_CARD_NUMBER
CRYPTO_WALLET_ADDRESS
DATE_OF_BIRTH
DEVICE_ID
DRIVER_LICENSE_NUMBER
EMAIL_ADDRESS
FACE_SCAN
FINGERPRINT
GENERAL_BIO
GENERAL_FINANCIAL
GENERAL_MEDICAL
GENERAL_PERSONAL
GENERAL_SOCIAL
GEOLOCATION_DATA
HEALTH_INSURANCE_ID
HOME_ADDRESS
IP_ADDRESS
MEDICAL_RECORD_NUMBER
MOTHER_MAIDEN_NAME
ONLINE_BEHAVIORAL_DATA
PASSPORT_NUMBER
PAYPAL_ACCOUNT
PHONE_NUMBER
PRESCRIPTION_DETAILS
ROUTING_NUMBER
SOCIAL_MEDIA_HANDLE
SOCIAL_MEDIA_PROFILE
SOCIAL_SECURITY_NUMBER
TAX_ID_NUMBER
THIRD_PARTY_BUSINESS_DATA
THIRD_PARTY_CUSTOMER_DATA
UNKNOWN
VOICE_PRINT
}
class ProductStateTypes #FAFF91 {
ARCHIVED
CERTIFIED
COMPANY_OWNED
CUSTOMER_OWNED
DEMO
DISCONTINUED
IN_TRANSIT
NEW
PARTNER_OWNED
REFURBISHED
RENTAL
THIRD_PARTY_OWNED
UNKNOWN
USED
}
class ProductViewTypes #FAFF91 {
CONTRACTUAL
INSTANCE
ONE_TIME
PROMOTIONAL
RECURRING
TEMPLATE
}
class RoleTypes #FAFF91 {
ADVISOR
AUTONOMOUS_SYSTEM
BUSINESS_DEVELOPMENT
CLOSING_MGR
CONCIERGE_MGR
CONCIERGE_STAFF
DISPATCHER
FINANCE
FI_MGR
GEN_MGR
HELPER_TECHNICIAN
INSPECTOR
MOBILE_DISPATCHER
MOBILE_SERVICE_VAN
PRIMARY_TECHNICIAN
QUALITY_CONTROL
SALES_ASSOC
SALES_MGR
SERVICE_ADVISOR
SERVICE_MGR
SERVICE_TECH
SPECIALIST
STAFF
SUBLET_VENDOR
TECHNICIAN
TOW_TRUCK
VALET
VALET_DRIVER
VALET_OPERATOR
}
class SkillCategoryTypes #FAFF91 {
AUTONOMOUS_SOFTWARE
BODY_STRUCTURAL
ELECTRICAL_EV
FLEET_LOGISTICS
MECHANICAL
}
class StaffPayTypes #FAFF91 {
ADJUSTMENT
BONUS
COMMISSION
CONTRACTOR
HOURLY
OTHER
OVERTIME
REGULAR
SALARIED
SICK
TECHNICIAN_HOURS
VACATION
}
class TimeslotDirectiveTypes #FAFF91 {
AFTER
ANYTIME
BEFORE
BETWEEN
BLOCK
UNKNOWN
}
class UnitOfMeasureTypes #FAFF91 {
BI_WEEKS
BYTES
CELSIUS
CITY
COUNTRY
COUNTY
CURRENCY
CUSTOM
DATE
DATE_TIME
DAYS
DAY_OF_MONTH
DISTRICT
DURATION
FAHRENHEIT
FATHOM
FEDERAL
FEET
GALLON
GROSS
HOURS
INCH
ITEM
KELVIN
KG
KM
LB
LITER
LOCALITY
MAXIMUM
METER
MILES
MINIMUM
MINUTES
MONTHS
MULTI_YEARS
NA
NAUTICAL
NET
NONE
OCCURRENCE
OTHER
OZ
PERCENT
POINTS
POSTAL
QUARTER
QUARTERS
RANKINE
SEMI_MONTHS
SEMI_YEARS
STATE
STREET
SUB_ADMIN_AREA
SUB_LOCALITY
UNIT
UNLIMITED
WATT
WEEKS
YARD
YEARS
}
class ValidationTypes #FAFF91 {
COMPLIANCE
CUSTOM
EXTENSIVE
LOOSE
MINIMUM
NONE
OVERRIDE
STANDARD
STRICT
TRUSTED
UNKNOWN
}
AddressReference *-- PartyReference
AddressTypes *-- AddressReference
Authorization *-- CommunicationChannel
BusinessTypes -- OrgProfile
Code *-- ControlAccountReference
Code *-- DepartmentReference
Code *-- Discount
Code *-- DiscountMetricValue
Code *-- EffectivePeriod
Code *-- GarageItem
Code *-- Identifier
Code *-- MetricNameValue
Code *-- MetricValue
Code *-- OrgProfile
Code *-- PersonReference
Code *-- ProductModel
Code *-- StaffAffinity
Code *-- StaffMember
Code *-- TextualDetail
Code *-- VehicleIdentifier
CommunicationChannelTypes -- CommunicationChannel
CommunicationChannel *-- ContactMethod
CommunicationChannel *-- PartyReference
CommunicationChannel *-- Person
CommunicationChannel *-- StaffMember
ContactMethod *-- Party
ControlAccountReference -- Discount
ControlAccountReference *-- OrgProfile
CurrencyExchange -- Money
CurrencyExchange -- Price
DaysOfWeekTypes -- TimeSlot
DepartmentReference -- StaffMember
DepartmentReference -- Team
DepartmentTypes -- DepartmentReference
DiscountMetricValue *-- Discount
DiscountTypes *-- Discount
Discount *-- DiscountPolicy
DueOnTypes -- Discount
DurationUOMTypes -- EffectivePeriod
EffectivePeriod -- DepartmentReference
EffectivePeriod -- Discount
EffectivePeriod -- GarageItem
EffectivePeriod -- PayrollRate
EffectivePeriod -- Price
EffectivePeriod -- TimeSlot
EffectivePeriod -- VehicleLicense
Garage -- Party
GarageItem *-- Garage
GenderTypes -- Person
Identifier -- ControlAccountReference
Identifier -- DepartmentReference
Identifier -- PartyReference
Identifier -- PaymentTermReference
Identifier -- PersonReference
Identifier *-- Discount
Identifier *-- Garage
Identifier *-- OrgProfile
Identifier *-- Party
Identifier *-- PaymentMethodReference
Identifier *-- Person
Identifier *-- PrivacyItem
Identifier *-- ProductModel
Identifier *-- StaffAffinity
Identifier *-- StaffMember
Identifier *-- TextualDetail
Identifier *-- VehicleIdentifier
Locale -- CommunicationChannel
MaritalStatusTypes -- Person
MetricNameValue *-- Person
MetricValue -- VehicleIdentifier
Money -- PayrollRate
NarrativeUomTypes -- MetricNameValue
NarrativeUomTypes -- MetricValue
OperatingStatusTypes -- OrgProfile
OrderCategoryTypes *-- Discount
OrgName -- OrgProfile
OrgProfile *-- Party
PartIdentifierTypes *-- OrgProfile
PartyReference *-- PayrollRate
PartyReference *-- StaffMember
PartyReference *-- Team
PartyRelationshipTypes *-- PartyReference
PartyRelationshipTypes -- PersonReference
PartyServiceTypes *-- Party
PartyTypes *-- Party
PartyTypes *-- Person
PayTypes -- Price
PaymentMethodReference *-- OrgProfile
PaymentMethodTypes -- PaymentMethodReference
PaymentTermReference *-- OrgProfile
PaymentTypes *-- Discount
PayrollCycleFrequencyTypes -- PayrollRate
PayrollRate *-- StaffMember
PersonName -- PartyReference
PersonName -- Person
PersonReference -- StaffMember
Person *-- Party
Price -- Discount
PriceTypes *-- Price
PrivacyContextTypes -- PrivacyEvent
PrivacyEvent *-- PrivacyItem
PrivacyItem *-- Person
PrivacyItem *-- StaffMember
PrivacyLegalBasisTypes -- PrivacyEvent
PrivacyStateTypes -- PrivacyEvent
PrivacyTypes -- PrivacyItem
ProductModel -- VehicleIdentifier
ProductStateTypes *-- Discount
ProductViewTypes -- Discount
RoleTypes *-- StaffMember
SkillCategoryTypes -- StaffSkill
StaffMember *-- OrgProfile
StaffAffinity -- StaffMember
StaffCertification *-- StaffMember
StaffPayTypes -- PayrollRate
StaffSkill *-- StaffMember
Team *-- StaffMember
TextualDetail *-- Discount
TextualDetail *-- PayrollRate
TimeSlot -- EffectivePeriod
TimeSlot *-- StaffAffinity
TimeslotDirectiveTypes *-- TimeSlot
UnitOfMeasureTypes -- DiscountMetricValue
ValidationTypes -- Discount
VehicleIdentifier -- GarageItem
VehicleLicense -- VehicleIdentifier
@enduml
