@startuml
rectangle "AddressReference" as AddressReference
rectangle "ColorDetail" as ColorDetail
rectangle "CreditApplicationReference" as CreditApplicationReference
rectangle "EffectivePeriod" as EffectivePeriod
rectangle "EventMessage" as EventMessage
rectangle "Identifier" as Identifier
rectangle "Insurance" as Insurance
rectangle "LeaseTerm" as LeaseTerm
rectangle "LifecycleEvent" as LifecycleEvent
rectangle "LifecyclePulse" as LifecyclePulse
rectangle "Locale" as Locale
rectangle "Manifest" as Manifest
rectangle "ManifestItem" as ManifestItem
rectangle "Media" as Media
rectangle "MetricValue" as MetricValue
rectangle "PartyReference" as PartyReference
rectangle "Position" as Position
rectangle "Price" as Price
rectangle "PriceSummary" as PriceSummary
rectangle "RetailDeliveryReport" as RetailDeliveryReport
rectangle "ShipmentReference" as ShipmentReference
rectangle "UnitOfMeasure" as UnitOfMeasure
rectangle "Vehicle" as Vehicle
rectangle "VehicleComponent" as VehicleComponent
rectangle "VehicleEconomy" as VehicleEconomy
rectangle "VehicleEvent" as VehicleEvent
rectangle "VehicleIdentifier" as VehicleIdentifier
rectangle "VehicleLicense" as VehicleLicense
rectangle "VehicleMedia" as VehicleMedia
rectangle "VehicleOption" as VehicleOption
rectangle "VehiclePriceSummary" as VehiclePriceSummary
rectangle "VehicleSpecification" as VehicleSpecification
rectangle "Warranty" as Warranty
rectangle "AddressTypes" as AddressTypes #FAFF91
rectangle "ApplicationStatusTypes" as ApplicationStatusTypes #FAFF91
rectangle "CabTypes" as CabTypes #FAFF91
rectangle "ControlAccountTypes" as ControlAccountTypes #FAFF91
rectangle "DealStatusTypes" as DealStatusTypes #FAFF91
rectangle "DurationUOMTypes" as DurationUOMTypes #FAFF91
rectangle "EngineTypes" as EngineTypes #FAFF91
rectangle "EventMessageTypes" as EventMessageTypes #FAFF91
rectangle "FuelTypes" as FuelTypes #FAFF91
rectangle "InsuranceTypes" as InsuranceTypes #FAFF91
rectangle "InventoryStatusTypes" as InventoryStatusTypes #FAFF91
rectangle "LeadStatusTypes" as LeadStatusTypes #FAFF91
rectangle "LifecycleEventTypes" as LifecycleEventTypes #FAFF91
rectangle "LifecyclePulseTypes" as LifecyclePulseTypes #FAFF91
rectangle "MediaDeliveryMethodTypes" as MediaDeliveryMethodTypes #FAFF91
rectangle "MediaFormatTypes" as MediaFormatTypes #FAFF91
rectangle "MediaTypes" as MediaTypes #FAFF91
rectangle "MediaUsageTypes" as MediaUsageTypes #FAFF91
rectangle "NarrativeUomTypes" as NarrativeUomTypes #FAFF91
rectangle "OemRdrStatusTypes" as OemRdrStatusTypes #FAFF91
rectangle "OptionTypes" as OptionTypes #FAFF91
rectangle "OrderCategoryTypes" as OrderCategoryTypes #FAFF91
rectangle "PartConditionTypes" as PartConditionTypes #FAFF91
rectangle "PartyRelationshipTypes" as PartyRelationshipTypes #FAFF91
rectangle "PartyTypes" as PartyTypes #FAFF91
rectangle "PayTypes" as PayTypes #FAFF91
rectangle "PaymentTypes" as PaymentTypes #FAFF91
rectangle "PriceTypes" as PriceTypes #FAFF91
rectangle "ProductStateTypes" as ProductStateTypes #FAFF91
rectangle "ProductTypes" as ProductTypes #FAFF91
rectangle "PurchaseTypes" as PurchaseTypes #FAFF91
rectangle "ResourceTypes" as ResourceTypes #FAFF91
rectangle "StaffRoleTypes" as StaffRoleTypes #FAFF91
rectangle "UOMLengthTypes" as UOMLengthTypes #FAFF91
rectangle "UOMQuantityCategoryTypes" as UOMQuantityCategoryTypes #FAFF91
rectangle "VehicleBodyStyleTypes" as VehicleBodyStyleTypes #FAFF91
rectangle "VehicleCategoryTypes" as VehicleCategoryTypes #FAFF91
rectangle "VehicleHistoryEventTypes" as VehicleHistoryEventTypes #FAFF91
rectangle "VehicleResourceTypes" as VehicleResourceTypes #FAFF91
AddressReference *-- PartyReference
AddressTypes *-- AddressReference
ApplicationStatusTypes -- CreditApplicationReference
CabTypes -- VehicleSpecification
ColorDetail -- Vehicle
ColorDetail -- VehicleSpecification
ControlAccountTypes -- Vehicle
CreditApplicationReference -- RetailDeliveryReport
DealStatusTypes -- RetailDeliveryReport
DurationUOMTypes -- EffectivePeriod
EffectivePeriod -- PartyReference
EffectivePeriod -- Price
EffectivePeriod -- ShipmentReference
EffectivePeriod -- VehicleEvent
EffectivePeriod -- VehicleLicense
EngineTypes *-- VehicleSpecification
EventMessageTypes -- EventMessage
EventMessage *-- RetailDeliveryReport
FuelTypes *-- VehicleEconomy
FuelTypes *-- VehicleSpecification
Identifier -- PartyReference
Identifier -- ShipmentReference
Identifier *-- Insurance
Identifier *-- Locale
Identifier *-- Vehicle
Identifier *-- VehicleIdentifier
Identifier *-- Warranty
InsuranceTypes -- Insurance
Insurance *-- Vehicle
InventoryStatusTypes *-- Vehicle
LeadStatusTypes -- RetailDeliveryReport
LeaseTerm -- RetailDeliveryReport
LifecycleEventTypes -- LifecycleEvent
LifecycleEvent *-- CreditApplicationReference
LifecyclePulseTypes *-- LifecyclePulse
LifecyclePulse *-- Manifest
Locale -- CreditApplicationReference
Locale -- PartyReference
Locale -- PriceSummary
Locale -- RetailDeliveryReport
ManifestItem *-- Manifest
Manifest *-- LeaseTerm
Manifest *-- RetailDeliveryReport
Manifest *-- VehicleComponent
MediaDeliveryMethodTypes -- Media
MediaFormatTypes -- Media
MediaTypes -- Media
MediaUsageTypes -- Media
Media *-- Vehicle
MetricValue -- Insurance
MetricValue -- RetailDeliveryReport
MetricValue -- Vehicle
MetricValue -- VehicleEconomy
MetricValue -- VehicleEvent
MetricValue -- VehicleIdentifier
MetricValue -- VehicleSpecification
MetricValue -- Warranty
MetricValue *-- VehicleComponent
NarrativeUomTypes -- MetricValue
OemRdrStatusTypes -- RetailDeliveryReport
OptionTypes -- VehicleOption
OrderCategoryTypes -- VehiclePriceSummary
PartConditionTypes -- Vehicle
PartyReference -- Insurance
PartyReference *-- CreditApplicationReference
PartyReference *-- Media
PartyReference *-- RetailDeliveryReport
PartyRelationshipTypes *-- PartyReference
PartyTypes -- RetailDeliveryReport
PayTypes -- Price
PaymentTypes -- VehiclePriceSummary
Position -- Vehicle
Position -- VehicleEvent
Price -- LeaseTerm
Price -- VehiclePriceSummary
PriceSummary -- CreditApplicationReference
PriceSummary -- Insurance
PriceSummary -- Vehicle
PriceSummary -- VehicleOption
PriceTypes *-- Price
Price *-- PriceSummary
ProductStateTypes -- Vehicle
ProductTypes *-- VehicleOption
PurchaseTypes -- RetailDeliveryReport
ResourceTypes -- LifecycleEvent
ResourceTypes -- PriceSummary
ShipmentReference -- RetailDeliveryReport
StaffRoleTypes -- EventMessage
UOMLengthTypes -- LeaseTerm
UOMQuantityCategoryTypes -- UnitOfMeasure
UnitOfMeasure *-- ShipmentReference
Vehicle -- RetailDeliveryReport
VehicleBodyStyleTypes *-- VehicleSpecification
VehicleCategoryTypes *-- VehicleSpecification
VehicleComponent *-- Vehicle
VehicleEconomy *-- Vehicle
VehicleEconomy *-- VehicleSpecification
VehicleEvent *-- Vehicle
VehicleHistoryEventTypes -- Vehicle
VehicleHistoryEventTypes -- VehicleEvent
VehicleIdentifier -- Insurance
VehicleIdentifier -- RetailDeliveryReport
VehicleIdentifier -- Vehicle
VehicleLicense -- Vehicle
VehicleLicense -- VehicleIdentifier
VehicleMedia *-- Vehicle
VehicleOption *-- Vehicle
VehiclePriceSummary *-- Vehicle
VehiclePriceSummary -- Vehicle
VehicleResourceTypes *-- VehicleSpecification
VehicleResourceTypes -- VehicleComponent
VehicleSpecification -- Vehicle
Warranty *-- Vehicle
@enduml
