@startuml
rectangle "AddressReference" as AddressReference
rectangle "Code" as Code
rectangle "CommunicationChannel" as CommunicationChannel
rectangle "CreditApplicationReference" as CreditApplicationReference
rectangle "DocumentReference" as DocumentReference
rectangle "EffectivePeriod" as EffectivePeriod
rectangle "EventMessage" as EventMessage
rectangle "Feature" as Feature
rectangle "Identifier" as Identifier
rectangle "Insurance" as Insurance
rectangle "LeaseTerm" as LeaseTerm
rectangle "LifecycleEvent" as LifecycleEvent
rectangle "LifecyclePulse" as LifecyclePulse
rectangle "Locale" as Locale
rectangle "Manifest" as Manifest
rectangle "ManifestItem" as ManifestItem
rectangle "MetricValue" as MetricValue
rectangle "Option" as Option
rectangle "PartyReference" as PartyReference
rectangle "PaymentScheduleReference" as PaymentScheduleReference
rectangle "PersonName" as PersonName
rectangle "Position" as Position
rectangle "Price" as Price
rectangle "PriceSummary" as PriceSummary
rectangle "ProductContract" as ProductContract
rectangle "RetailDeliveryReport" as RetailDeliveryReport
rectangle "RetailDeliveryReportCriteria" as RetailDeliveryReportCriteria
rectangle "ShipmentReference" as ShipmentReference
rectangle "UnitOfMeasure" as UnitOfMeasure
rectangle "Vehicle" as Vehicle
rectangle "VehicleEvent" as VehicleEvent
rectangle "VehicleIdentifier" as VehicleIdentifier
rectangle "VehiclePriceSummary" as VehiclePriceSummary
rectangle "VehicleSpecification" as VehicleSpecification
rectangle "Warranty" as Warranty
rectangle "AddressTypes" as AddressTypes #FAFF91
rectangle "ApplicationStatusTypes" as ApplicationStatusTypes #FAFF91
rectangle "CabTypes" as CabTypes #FAFF91
rectangle "CommunicationChannelTypes" as CommunicationChannelTypes #FAFF91
rectangle "ContractStatusTypes" as ContractStatusTypes #FAFF91
rectangle "ContractTypes" as ContractTypes #FAFF91
rectangle "ControlAccountTypes" as ControlAccountTypes #FAFF91
rectangle "DealStatusTypes" as DealStatusTypes #FAFF91
rectangle "DocumentTypes" as DocumentTypes #FAFF91
rectangle "DurationIntervalTypes" as DurationIntervalTypes #FAFF91
rectangle "DurationUOMTypes" as DurationUOMTypes #FAFF91
rectangle "EngineTypes" as EngineTypes #FAFF91
rectangle "EventMessageTypes" as EventMessageTypes #FAFF91
rectangle "FuelTypes" as FuelTypes #FAFF91
rectangle "InsuranceTypes" as InsuranceTypes #FAFF91
rectangle "InventoryStatusTypes" as InventoryStatusTypes #FAFF91
rectangle "LeadStatusTypes" as LeadStatusTypes #FAFF91
rectangle "LifecycleEventTypes" as LifecycleEventTypes #FAFF91
rectangle "LifecyclePulseTypes" as LifecyclePulseTypes #FAFF91
rectangle "NarrativeUomTypes" as NarrativeUomTypes #FAFF91
rectangle "OemRdrStatusTypes" as OemRdrStatusTypes #FAFF91
rectangle "OptionInstallationTypes" as OptionInstallationTypes #FAFF91
rectangle "OptionTypes" as OptionTypes #FAFF91
rectangle "OrderCategoryTypes" as OrderCategoryTypes #FAFF91
rectangle "PartConditionTypes" as PartConditionTypes #FAFF91
rectangle "PartyRelationshipTypes" as PartyRelationshipTypes #FAFF91
rectangle "PartyTypes" as PartyTypes #FAFF91
rectangle "PayTypes" as PayTypes #FAFF91
rectangle "PaymentTypes" as PaymentTypes #FAFF91
rectangle "PriceTypes" as PriceTypes #FAFF91
rectangle "ProductStateTypes" as ProductStateTypes #FAFF91
rectangle "ProductTypes" as ProductTypes #FAFF91
rectangle "PurchaseTypes" as PurchaseTypes #FAFF91
rectangle "ResourceTypes" as ResourceTypes #FAFF91
rectangle "StaffRoleTypes" as StaffRoleTypes #FAFF91
rectangle "UOMLengthTypes" as UOMLengthTypes #FAFF91
rectangle "UOMQuantityCategoryTypes" as UOMQuantityCategoryTypes #FAFF91
rectangle "VehicleBodyStyleTypes" as VehicleBodyStyleTypes #FAFF91
rectangle "VehicleCategoryTypes" as VehicleCategoryTypes #FAFF91
rectangle "VehicleHistoryEventTypes" as VehicleHistoryEventTypes #FAFF91
rectangle "VehicleResourceTypes" as VehicleResourceTypes #FAFF91
AddressReference *-- PartyReference
AddressTypes *-- AddressReference
ApplicationStatusTypes -- CreditApplicationReference
CabTypes -- VehicleSpecification
Code *-- EffectivePeriod
Code *-- Identifier
Code *-- Insurance
Code *-- MetricValue
Code *-- Option
Code *-- PartyReference
Code *-- ProductContract
Code *-- RetailDeliveryReport
Code *-- RetailDeliveryReportCriteria
Code *-- ShipmentReference
Code *-- Vehicle
Code *-- VehicleEvent
Code *-- VehicleIdentifier
Code *-- Warranty
CommunicationChannelTypes -- CommunicationChannel
CommunicationChannel *-- PartyReference
ContractStatusTypes -- ProductContract
ContractTypes *-- ProductContract
ControlAccountTypes -- Vehicle
CreditApplicationReference -- RetailDeliveryReport
CreditApplicationReference -- RetailDeliveryReportCriteria
DealStatusTypes -- RetailDeliveryReportCriteria
DocumentReference *-- ProductContract
DocumentTypes -- DocumentReference
DurationIntervalTypes -- PaymentScheduleReference
DurationUOMTypes -- EffectivePeriod
EffectivePeriod -- PartyReference
EffectivePeriod -- PaymentScheduleReference
EffectivePeriod -- Price
EffectivePeriod -- ProductContract
EffectivePeriod -- ShipmentReference
EffectivePeriod -- VehicleEvent
EngineTypes *-- VehicleSpecification
EventMessageTypes -- EventMessage
EventMessage *-- LifecyclePulse
EventMessage *-- RetailDeliveryReport
Feature *-- Vehicle
FuelTypes *-- VehicleSpecification
Identifier -- PartyReference
Identifier -- PaymentScheduleReference
Identifier -- RetailDeliveryReport
Identifier -- RetailDeliveryReportCriteria
Identifier *-- Insurance
Identifier *-- ProductContract
Identifier *-- RetailDeliveryReport
Identifier *-- RetailDeliveryReportCriteria
Identifier *-- Vehicle
Identifier *-- VehicleEvent
Identifier *-- VehicleIdentifier
Identifier *-- Warranty
InsuranceTypes -- Insurance
Insurance *-- Vehicle
InventoryStatusTypes *-- Vehicle
LeadStatusTypes -- RetailDeliveryReportCriteria
LeaseTerm -- RetailDeliveryReport
LifecycleEventTypes -- LifecycleEvent
LifecycleEvent *-- CreditApplicationReference
LifecyclePulseTypes *-- LifecyclePulse
LifecyclePulse *-- Manifest
Locale -- CommunicationChannel
Locale -- CreditApplicationReference
Locale -- PartyReference
Locale -- PriceSummary
Locale -- RetailDeliveryReport
Locale -- RetailDeliveryReportCriteria
ManifestItem *-- Manifest
Manifest *-- LeaseTerm
Manifest *-- RetailDeliveryReport
MetricValue -- Insurance
MetricValue -- Option
MetricValue -- ProductContract
MetricValue -- RetailDeliveryReport
MetricValue -- Vehicle
MetricValue -- VehicleEvent
MetricValue -- VehicleIdentifier
MetricValue -- VehicleSpecification
MetricValue -- Warranty
NarrativeUomTypes -- MetricValue
NarrativeUomTypes -- ProductContract
OemRdrStatusTypes -- RetailDeliveryReport
OemRdrStatusTypes -- RetailDeliveryReportCriteria
OptionInstallationTypes -- Option
OptionTypes -- Option
Option *-- Vehicle
OrderCategoryTypes -- VehiclePriceSummary
PartConditionTypes -- Vehicle
PartyReference -- Insurance
PartyReference -- ShipmentReference
PartyReference *-- CreditApplicationReference
PartyReference *-- ProductContract
PartyReference *-- RetailDeliveryReport
PartyReference *-- RetailDeliveryReportCriteria
PartyRelationshipTypes *-- PartyReference
PartyTypes -- RetailDeliveryReport
PartyTypes -- RetailDeliveryReportCriteria
PayTypes -- Price
PaymentScheduleReference -- ProductContract
PaymentTypes -- VehiclePriceSummary
PersonName -- PartyReference
Position -- Vehicle
Position -- VehicleEvent
Price -- LeaseTerm
Price -- VehiclePriceSummary
PriceSummary -- CreditApplicationReference
PriceSummary -- Insurance
PriceSummary -- Option
PriceSummary -- ProductContract
PriceSummary -- Vehicle
PriceTypes *-- Price
Price *-- PriceSummary
ProductContract *-- RetailDeliveryReport
ProductStateTypes *-- Vehicle
ProductStateTypes -- RetailDeliveryReport
ProductStateTypes -- RetailDeliveryReportCriteria
ProductTypes *-- Option
PurchaseTypes -- RetailDeliveryReport
PurchaseTypes -- RetailDeliveryReportCriteria
ResourceTypes -- LifecycleEvent
ResourceTypes -- PriceSummary
RetailDeliveryReportCriteria -- RetailDeliveryReport
ShipmentReference -- RetailDeliveryReport
StaffRoleTypes -- EventMessage
UOMLengthTypes -- LeaseTerm
UOMQuantityCategoryTypes -- UnitOfMeasure
UnitOfMeasure *-- ShipmentReference
Vehicle -- RetailDeliveryReport
VehicleBodyStyleTypes *-- VehicleSpecification
VehicleCategoryTypes *-- VehicleSpecification
VehicleEvent *-- Vehicle
VehicleHistoryEventTypes -- Vehicle
VehicleHistoryEventTypes -- VehicleEvent
VehicleIdentifier -- Insurance
VehicleIdentifier -- RetailDeliveryReportCriteria
VehicleIdentifier -- Vehicle
VehiclePriceSummary *-- Vehicle
VehiclePriceSummary -- Vehicle
VehicleResourceTypes *-- VehicleSpecification
VehicleSpecification -- Vehicle
Warranty *-- Vehicle
@enduml
