@startuml
rectangle "CurrencyExchange" as CurrencyExchange
rectangle "Identifier" as Identifier
rectangle "Money" as Money
rectangle "Payment" as Payment
rectangle "PaymentMethodReference" as PaymentMethodReference
rectangle "PaymentTransaction" as PaymentTransaction
rectangle "PaymentAmountTypes" as PaymentAmountTypes #FAFF91
rectangle "PaymentMethodTypes" as PaymentMethodTypes #FAFF91
rectangle "PaymentStatusTypes" as PaymentStatusTypes #FAFF91
rectangle "PaymentTransactionStatusTypes" as PaymentTransactionStatusTypes #FAFF91
CurrencyExchange -- Money
Identifier -- PaymentMethodReference
Money -- Payment
Money -- PaymentTransaction
PaymentAmountTypes -- PaymentTransaction
PaymentMethodReference -- PaymentTransaction
PaymentMethodTypes -- PaymentMethodReference
PaymentStatusTypes -- Payment
PaymentTransactionStatusTypes -- PaymentTransaction
PaymentTransaction *-- Payment
@enduml
