@startuml
class AddressReference {
addressReferenceKey:String
addressReferenceValue:String
addressTypes:List<AddressTypes>
addressLine1:String
addressLine2:String
addressLine3:String
addressLine4:String
addressLine5:String
city:String
countryCode:String
district:String
label:String
postalCode:String
stateProvince:String
}
class Code {
codeId:String
codeKey:String
code:String
description:String
}
class ColorDetail {
colorDetailId:String
colorDetailKey:String
dealerColor:String
descColor:String
colorCode:String
oemName:String
marketingName:String
}
class CommunicationChannel {
communicationChannelKey:String
communicationChannelId:String
communicationChannelType:CommunicationChannelTypes
value:String
valueExtension:String
label:String
locale:Locale
preferredIndicator:Boolean
preferences:List<TimeSlot>
authorizations:List<Authorization>
}
class CreditApplicationReference {
creditApplicationReferenceId:String
creditApplicationReferenceKey:String
creditApplicationKey:String
creditParties:List<PartyReference>
locale:Locale
occurrenceDateTime:Date
creditApplicationName:String
creditApplicationDate:Date
confirmationCode:String
applicationStatusType:ApplicationStatusTypes
creditApplicationEvents:List<LifecycleEvent>
priceSummary:PriceSummary
}
class DocumentReference {
documentReferenceId:String
documentReferenceKey:String
documentId:String
documentDateTime:Date
documentIdentificationContext:String
documentType:DocumentTypes
}
class EffectivePeriod {
effectivePeriodKey:String
activeIndicator:Boolean
exclusiveIndicator:Boolean
startDateTime:Date
completeDateTime:Date
durationUomType:DurationUOMTypes
durationValue:String
recurUomType:DurationUOMTypes
recurCount:String
recurValues:List<Code>
recurCriteria:String
recurIndicator:Boolean
timeslot:TimeSlot
}
class EventMessage {
eventMessageKey:String
eventMessageId:String
eventActorKey:String
eventActorName:String
eventActorRoleType:StaffRoleTypes
eventDateTime:Date
eventMessageGroup:String
eventMessageDesc:String
eventMessageType:EventMessageTypes
eventMessageName:String
eventMessageCode:String
eventMessageValue:String
internalIndicator:Boolean
}
class Feature {
featureId:String
featureKey:String
header:String
description:String
featureDetails:List<FeatureItem>
}
class Identifier {
identifierId:String
identifierKey:String
context:String
value:String
detail:String
identifierType:String
systemCodes:List<Code>
}
class Insurance {
insuranceKey:String
insuranceId:String
insuranceType:InsuranceTypes
insuranceCompany:PartyReference
insuranceAgent:PartyReference
identifiers:List<Identifier>
vehicleIdentifier:VehicleIdentifier
planCodes:List<Code>
planTypes:List<Code>
agreementNumber:String
insurancePolicyNumber:String
effectiveDate:Date
expirationDate:Date
planCoverage:MetricValue
expirationMileage:MetricValue
insuredPersonName:String
description:String
confirmationCode:String
policyHolder:PolicyHolder
insuranceTerms:List<InsuranceTerm>
links:List<Link>
priceSummary:PriceSummary
}
class LeaseTerm {
leaseTermId:String
leaseTermKey:String
termMonths:Integer
moneyFactor:String
residualValue:Price
mileageAllowance:UOMLengthTypes
grossCapitalizedCost:Price
termManifests:List<Manifest>
}
class LifecycleEvent {
lifecycleEventId:String
lifecycleEventKey:String
actorHref:String
actorId:String
actorName:String
lifecycleEventType:LifecycleEventTypes
occurrenceDate:Date
resourceHref:String
resourceIdentifier:String
detailName:String
detailDesc:String
detailValue:String
detailKey:String
detailCode:String
resourceTypes:ResourceTypes
}
class LifecyclePulse {
lifecyclePulseId:String
lifecyclePulseKey:String
lifecyclePulseTypes:List<LifecyclePulseTypes>
occurredAt:Date
actorName:String
executionId:String
}
class Locale {
localeId:String
localeKey:String
localeName:String
description:String
languageCode:String
countryCode:String
currencyCode:String
currencySymbol:String
timezone:String
numberFormat:String
identifiers:List<Identifier>
locationCode:String
}
class Manifest {
manifestId:String
manifestKey:String
context:String
schema:String
definitions:List<ManifestItem>
lifecyclePulses:List<LifecyclePulse>
manifestType:String
version:String
}
class ManifestItem {
manifestItemId:String
manifestItemKey:String
context:String
id:String
value:String
description:String
}
class MetricValue {
metricValueId:String
metricValueKey:String
value:String
uom:NarrativeUomTypes
codes:List<Code>
}
class Option {
optionId:String
optionKey:String
codes:List<Code>
optionName:String
optionLongName:String
manufacturerName:String
shortDescription:String
priceSummary:PriceSummary
productTypes:List<ProductTypes>
quantity:MetricValue
optionType:OptionTypes
optionInstallationType:OptionInstallationTypes
optionCode:String
optionCategories:List<Code>
optionGroups:List<Code>
optionDescriptions:List<OptionDescription>
}
class PartyReference {
partyReferenceId:String
partyReferenceKey:String
partyKey:String
partyName:String
contactName:PersonName
locale:Locale
authorizationCode:String
sourceSystemCode:String
context:String
accountNumber:String
partyRelationshipTypes:List<PartyRelationshipTypes>
systemCodes:List<Code>
ruleCodes:List<Code>
party:Identifier
occurrenceDateTime:Date
duration:EffectivePeriod
addressReferences:List<AddressReference>
communicationChannels:List<CommunicationChannel>
}
class PaymentScheduleReference {
paymentScheduleReferenceId:String
paymentScheduleReferenceKey:String
paymentScheduleKey:String
paymentPeriod:EffectivePeriod
context:String
totalPayments:Integer
identifier:Identifier
occurrenceDateTime:Date
paymentFrequency:DurationIntervalTypes
paymentAmount:String
annualPercentageRate:String
}
class PersonName {
alias:String
familyName:String
fullName:String
givenName:String
identifiersHref:String
maidenName:String
middleName:String
nameSuffix:String
partyKey:String
personKey:String
personNameKey:String
preferredName:String
salutation:String
honorificPrefix:String
honorificSuffix:String
locale:String
phoneticFamilyName:String
phoneticGivenName:String
phoneticMiddleName:String
nationality:String
}
class Position {
positionId:String
positionKey:String
latitude:String
longitude:String
altitude:String
bearing:String
postalCode:String
countyCode:String
}
class Price {
displayValue:String
locale:String
value:String
taxValue:String
taxableAmount:String
nonTaxableAmount:String
totalAmount:String
totalCostAmount:String
unitCostAmount:String
priceDescription:String
priceKey:String
taxIncludedIndicator:Boolean
currencyCode:String
priceId:String
duration:EffectivePeriod
priceTypes:List<PriceTypes>
payType:PayTypes
currencyExchange:CurrencyExchange
}
class PriceSummary {
priceSummaryKey:String
priceSummaryId:String
sourceKey:String
sourceType:ResourceTypes
locale:Locale
prices:List<Price>
}
class ProductContract {
productContractId:String
productContractKey:String
partyReferences:List<PartyReference>
contractNumber:String
executionDate:Date
expirationDate:Date
effectivePeriod:EffectivePeriod
expirationDistance:MetricValue
termUnits:NarrativeUomTypes
termValue:String
quantity:String
capitalizationIndicator:Boolean
financedIndicator:Boolean
taxabilityIndicator:Boolean
priceSummary:PriceSummary
codes:List<Code>
contractTypes:List<ContractTypes>
identifiers:List<Identifier>
documentReference:List<DocumentReference>
contractStatusType:ContractStatusTypes
paymentScheduleReference:PaymentScheduleReference
}
class ProductModel {
productModelKey:String
productModelId:String
identifiers:List<Identifier>
brands:List<Code>
trims:List<Code>
marketingNames:List<Code>
oemNames:List<Code>
oemCodes:List<Code>
modelCodes:List<Code>
phaseCode:String
nicknames:List<Code>
tags:List<Code>
}
class RetailDeliveryReport {
retailDeliveryReportId:String
retailDeliveryReportKey:String
rdrSource:String
manifests:List<Manifest>
locale:Locale
partyReferences:List<PartyReference>
eventMessages:List<EventMessage>
occurrenceDateTime:Date
OemRdrStatusType:OemRdrStatusTypes
leadStatusType:LeadStatusTypes
dealStatusType:DealStatusTypes
odometerAtSale:MetricValue
rdrCodes:List<Code>
salesCode:Identifier
warrantyCodes:List<Identifier>
transmittedSalesCode:Identifier
productStateType:ProductStateTypes
purchaseType:PurchaseTypes
partyType:PartyTypes
vehicleIdentifier:VehicleIdentifier
saleDate:Date
salesTransactionNumber:String
deliveryEstimate:ShipmentReference
leaseTerm:LeaseTerm
creditApplicationReference:CreditApplicationReference
vehicle:Vehicle
identifiers:List<Identifier>
productContracts:List<ProductContract>
creditContractIncludedIndicator:Boolean
retailDeliveryReportCriteria:RetailDeliveryReportCriteria
}
class RetailDeliveryReportCriteria {
retailDeliveryReportCriteriaId:String
retailDeliveryReportCriteriaKey:String
rdrSource:String
locale:Locale
partyReferences:List<PartyReference>
OemRdrStatusType:OemRdrStatusTypes
leadStatusType:LeadStatusTypes
dealStatusType:DealStatusTypes
rdrCodes:List<Code>
salesCode:Identifier
warrantyCodes:List<Identifier>
transmittedSalesCode:Identifier
productStateType:ProductStateTypes
purchaseType:PurchaseTypes
partyType:PartyTypes
vehicleIdentifier:VehicleIdentifier
saleDate:Date
salesTransactionNumber:String
creditApplicationReference:CreditApplicationReference
}
class ShipmentReference {
shipmentReferenceId:String
shipmentReferenceKey:String
shipmentKey:String
trackingNumber:String
context:String
systemCodes:List<Code>
carrierParty:PartyReference
occurrenceDateTime:Date
unitOfMeasures:List<UnitOfMeasure>
estimatedDelivery:EffectivePeriod
}
class UnitOfMeasure {
unitOfMeasureKey:String
unitName:String
uomValue:String
uomQuantityCategoryType:UOMQuantityCategoryTypes
}
class Vehicle {
vehicleKey:String
vehicleId:String
vehicleIdentifier:VehicleIdentifier
stockNumber:String
axleCount:String
odometer:MetricValue
deliveredDateTime:Date
seats:String
conditionType:PartConditionTypes
exteriorColor:ColorDetail
inventoryDays:String
campaignCodes:List<Code>
position:Position
productionDate:Date
stockDateTime:Date
controlAccountId:String
controlAccountType:ControlAccountTypes
vehicleSpecification:VehicleSpecification
originalSoldDate:Date
odometerCaptureDate:Date
warranties:List<Warranty>
hardwareCodes:List<Code>
softwareCodes:List<Code>
priceSummary:PriceSummary
dealerCode:String
accountKey:String
accountName:String
inventoryStatusTypes:List<InventoryStatusTypes>
productStateType:List<ProductStateTypes>
vehicleStatusType:VehicleHistoryEventTypes
standardOptions:List<Option>
safetyRatings:List<Option>
features:List<Feature>
interiorColor:ColorDetail
comments:String
vehicleNotes:String
categories:List<Code>
vehiclePriceSummary:VehiclePriceSummary
vehiclePriceSummaries:List<VehiclePriceSummary>
vehicleEconomies:List<VehicleEconomy>
deliveryDate:Date
vehicleEvents:List<VehicleEvent>
identifiers:List<Identifier>
insurances:List<Insurance>
condition:String
vehicleComponents:List<VehicleComponent>
}
class VehicleComponent {
vehicleComponentId:String
vehicleComponentKey:String
vehicleManifests:List<Manifest>
componentCodes:List<Code>
name:String
description:String
metricValues:List<MetricValue>
componentType:VehicleResourceTypes
}
class VehicleEconomy {
vehicleEconomyKey:String
efficiency:Efficiency
fuelTankCapacity:MetricValue
fuelTypes:List<FuelTypes>
range:MetricValue
}
class VehicleEvent {
vehicleEventKey:String
vehicleEventId:String
vehicleEventType:VehicleHistoryEventTypes
vehicleEventCodes:List<Code>
eventSource:String
eventDetail:String
eventDateTime:Date
eventDuration:EffectivePeriod
odometer:MetricValue
position:Position
positionDesc:String
eventSequenceNum:Integer
eventOrgCode:String
eventOrgPartyName:String
identifiers:List<Identifier>
}
class VehicleIdentifier {
vehicleIdentifierKey:String
vehicleIdentifierId:String
odometer:MetricValue
vehicleKey:String
unitId:String
stockNumber:String
identifiers:List<Identifier>
license:VehicleLicense
make:String
model:String
brand:String
trim:String
oemModelCode:String
oemName:String
oemCode:String
modelCode:String
modelDescription:String
modelYear:String
vin:String
tags:List<Code>
modelDetail:ProductModel
}
class VehicleLicense {
vehicleLicenseKey:String
plateNumber:String
jurisdictionName:String
countryCode:String
effectivePeriod:EffectivePeriod
}
class VehiclePriceSummary {
vehiclePriceSummaryKey:String
vehiclePriceSummaryId:String
vehiclePriceName:String
vehiclePriceCriteriaName:String
price:Price
priceCode:String
capitalizedIndicator:Boolean
taxableIndicator:Boolean
taxSeparateIndicator:Boolean
paymentType:PaymentTypes
purchaseType:OrderCategoryTypes
}
class VehicleSpecification {
vehicleSpecificationKey:String
axleCount:String
backupCameraIndicator:Boolean
bodyHeight:String
bodyLength:String
bodyStyle:String
bodyWidth:String
boxTypeDescription:String
bulkhead:String
cabType:CabTypes
compartmentDepth:String
condition:String
craneIndicator:Boolean
cylinderCount:String
doorsCount:String
driveTrain:String
energyImpactScore:String
engineTypeDescription:String
engineTypes:List<EngineTypes>
exteriorColor:ColorDetail
exteriorLightsIndicator:Boolean
floorDesc:String
floorDescDetail:String
fuelTypes:List<FuelTypes>
grossVehicleWeight:MetricValue
grossVehicleWeightRating:MetricValue
hitchIndicator:Boolean
powerTrain:String
horsePower:String
insideBodyHeight:String
insideBodyWidth:String
insideLength:String
interiorColor:ColorDetail
ladderRackDesc:String
liftgateIndicator:Boolean
make:String
manufacturerModelCode:String
manufacturerName:String
marketingDescription:String
merchandisingModelCode:String
model:String
modelCode:String
modelDescription:String
modelYear:String
seatingCapacity:String
seriesCode:String
sideHeight:String
snowplowIndicator:Boolean
stakePockets:String
torque:String
towingCapacity:MetricValue
transmission:String
trim:String
unladenVehicleWeight:MetricValue
upliftIndicator:Boolean
vehicleBodyStyleTypes:List<VehicleBodyStyleTypes>
vehicleCategoryTypes:List<VehicleCategoryTypes>
vehicleClass:String
vehicleEconomies:List<VehicleEconomy>
vehicleFuelCapacity:String
vehiclePto:String
vehicleRearWheels:String
vehicleTypeDescription:String
vehicleTypes:List<VehicleResourceTypes>
wheelBase:String
compartmentDoorDesc:String
}
class Warranty {
warrantyId:String
warrantyKey:String
delayedInspectionCodes:List<Code>
receiptIdentifiers:List<Code>
vehicleArrivalDate:Date
actualOdometerEnd:MetricValue
actualOdometerStart:MetricValue
warrantyTerms:List<WarrantyTerm>
warrantyCoverages:List<WarrantyCoverage>
warrantyCoverageCodes:List<Code>
locale:String
currency:String
identifiers:List<Identifier>
}
class AddressTypes #FAFF91 {
ARCHIVE
AR_ADDRESS
BILLING
BUSINESS
CONTRACT
CURRENT
DEALER
DELIVERY
DESTINATION
EMERGENCY
GARAGE
HOME
INSURANCE
LEGAL
MAILING
ORIGINAL
OTHER
POSTAL
PREVIOUS
PRODUCT
REBATE
RECIPIENT
RESIDENCE
SERVICE
SERVICE_CONTRACT
SHIPPING
TEMPORARY
VACATION
WORK
}
class ApplicationStatusTypes #FAFF91 {
ABANDON
ACTIVE
APPROVED
CANCELLED
CLOSE
COMPLETE
CUSTOMER_HOLD
DECLINED
FINANCE_HOLD
INACTIVE
INITIATING
INVALID
PAYMENT_HOLD
REJECT
SALES_HOLD
}
class CabTypes #FAFF91 {
CREW
EXTENDED
MEGA
REGULAR
}
class CommunicationChannelTypes #FAFF91 {
APP
BROADCAST
CELL
DIRECT_MAIL
EMAIL
OTHER
PDA
PHONE
SMS
SOCIAL_MEDIA
URL
VIDEO
VOICE
}
class ContractStatusTypes #FAFF91 {
APPROVED
BOOKED
CONDITIONAL
DECLINED
OTHER
PENDING
}
class ContractTypes #FAFF91 {
EXTENDED_WARRANTY
FINANCE
MAINTENANCE
OTHER
PROTECTION
SERVICE
WARRANTY
}
class ControlAccountTypes #FAFF91 {
ACCESSORIES
ASSETS
CLEARING
COGS
CONTRA_ASSET
CREDIT
CUSTOMER
DEALER
DEPRECIATION
DISCOUNT
EMPLOYEE
EQUITY
EXPENSE
FEE
FIXED_ASSETS
LIABILITY
LONG_TERM_LIABILITY
OPTION
OTHER
OTHER_INCOME
PACKAGE
PARTS_SALES_ORDER
PRODUCT
PROVISION
REBATE
REFERENCE
REPAIR_ORDER
REVENUE
ROUNDING
SERVICE
TAX
VEHICLE
VENDOR
}
class DealStatusTypes #FAFF91 {
ABANDONED
ACCEPTED
FUNDED
IN_PROGRESS
POSTED
REVERSED
}
class DocumentTypes #FAFF91 {
BIRTH_CERTIFICATE
CITIZENSHIP
CONSULAR_BIRTH_ABROAD
CORPORATE
COURT_DOCUMENT
CREDIT_CONTRACT
DRIVERS_LICENSE
EMPLOYMENT_AUTHORIZATION
GOVERNMENT
GROUP
INTERNATIONAL
MILITARY
NATURALIZATION
OTHER1
PASSPORT
PRODUCT_CONTRACT
PROFESSIONAL
RESIDENT
SOCIAL_SECURITY
STATE_ID
STUDENT
UNIFIED_MULTI_PURPOSE_ID
VISA
}
class DurationIntervalTypes #FAFF91 {
BI_WEEKLY
CUSTOM
DAILY
HOURLY
LIFETIME
MINUTES
MONTHLY
MULTI_YEAR
ONE_TIME
OTHER
QUARTERLY
RECUR
SEMI_MONTHLY
SEMI_YEAR
WEEKLY
YEARLY
}
class DurationUOMTypes #FAFF91 {
BI_WEEKS
CUSTOM
DAYS
DAY_OF_MONTH
HOURS
MINUTES
MONTHS
MULTI_YEARS
NONE
OCCURRENCE
OTHER
QUARTERS
SEMI_MONTHS
SEMI_YEARS
UNLIMITED
WEEKS
YEARS
}
class EngineTypes #FAFF91 {
ELECTRIC
HYBRID
ICE
OTHER
PHYSICAL
THERMAL_EXTERNAL
THERMAL_INTERNAL
THERMAL_REACTION
}
class EventMessageTypes #FAFF91 {
ACTION_CONFIRMATION
AUDIT
BROADCAST
COMPENSATION
CRITIQUE
DELEGATION
ERROR_REPORT
HEARTBEAT
INSTRUCTION
LOGGING
REASONING
RESPONSE
RETRY_SIGNAL
TOOL_CALL
TOOL_OUTPUT
UNKNOWN
}
class FuelTypes #FAFF91 {
AVIATION_GASOLINE_AVGAS
AVIATION_TURBINE_AVTUR
BIO_DIESEL
DIESEL
DIESEL_OID_MDF
ELECTRIC
ETHANOL
GASOLINE
HYDROGEN
KEROSENE
METHANOL
NATURAL_GAS
OTHER
PROPANE
P_SERIES
SOLAR_OIL_HSD
}
class InsuranceTypes #FAFF91 {
AUTO
BUSINESS_INTERRUPTION
COMMERCIAL_AUTO
CYBER_LIABILITY
DISABILITY
EVENT
FIRE
FLOOD
GUARANTEE
HEALTH
HOMEOWNERS
IDENTITY_THEFT_PROTECTION
LIABILITY
LIFE
LONG_TERM_CARE
LONG_TERM_DISABILITY
MARINE
OTHER
PERSONAL
PET
PROFESSIONAL_LIABILITY
PROPERTY
RENTERS
RENT_GUARANTEE
STORM
TERM_LIFE
TITLE
TRAVEL
UMBRELLA
WIND
WORKERS_COMPENSATION
}
class InventoryStatusTypes #FAFF91 {
ASSIGNED_BY_MANUFACTURER
AVAILABLE
DAMAGED
DISPOSAL
IN_TRANSIT
ON_CENTRAL_LOT
ON_DEALER_LOT
ON_HOLD
ON_ORDER
PREPARATION
PRE_SOLD
RECALL_HOLD
RECEIVED
RESERVED
RETURNED
SALES_HOLD
SERVICE_HOLD
SOLD
STOCKED_IN
UNAVAILABLE
UNKNOWN
WHOLESALE
}
class LeadStatusTypes #FAFF91 {
CONTACTED
CONTRACT_SENT
DEMO_GIVEN
DISQUALIFIED
FOLLOW_UP_SCHEDULED
IN_PROGRESS
LOST
NEGOTIATION
NEW
PROPOSAL_SENT
UNQUALIFIED
VERBAL_COMMITMENT
WON
}
class LifecycleEventTypes #FAFF91 {
ACCESS_ALLOWED
ACCESS_DENIED
ACKNOWLEDGMENT
CANCELLED
CLOSED
CREATED
DEAD
DELETE_HARD
DELETE_SOFT
FAILED
INCOMPLETE
INITIALIZED
INITIALIZING
PROCESSED
PROCESSING
QUALIFIED
QUEUED
REJECTED
STATUS_CHANGE
STEP_TRANSITION
SUBMITTED
UNQUALIFIED
UPDATED
VALIDATED
}
class LifecyclePulseTypes #FAFF91 {
ACKNOWLEDGED
ARCHIVED
CREATED
PROCESSED
REJECTED
STARTED
TRANSMITTED
UPDATED
VOIDED
}
class NarrativeUomTypes #FAFF91 {
AMPERE
ARRAY
BAR
BINARY
BI_WEEKS
BOOLEAN
CELSIUS
CENTIMETER
CODE
CUBIC_METER
CURRENCY
CUSTOM
DATE
DATE_TIME
DAYS
DAY_OF_MONTH
DEGREES
DESC
DOUBLE
DURATION
FAHRENHEIT
FATHOM
FEET
FLOAT
FLUID_OUNCE
GALLON
GRAMS
GROUP
G_FORCE
HOURS
HP
INCH
INT32
INT64
INTEGER
KELVIN
KEY
KG
KILOWATT_HOUR
KM
KPA
LABEL
LB
LITER
METER
MI
MILES
MILLIMETER
MINUTES
MONTHS
MULTI_YEARS
NAUTICAL
NONE
NUMBER
OBJECT
OCCURRENCE
OHM
OTHER
OZ
PERCENT
POINTS
PROTECTED_TEXT
PSI
QUARTERS
RANKINE
RPM
SECONDS
SEMI_MONTHS
SEMI_YEARS
STRING
TEXT
TIME
TONS
UNLIMITED
VOLT
WATT
WEEKS
YARD
YEARS
}
class OemRdrStatusTypes #FAFF91 {
APPROVED
CANCELLED
LOCKED
NEW_INTERFACE
OPEN
REJECTED
TRANSMITTED
}
class OptionInstallationTypes #FAFF91 {
ACCESSORY_KIT
CUSTOM_FABRICATION
DEALER_INSTALLED
FACTORY_INSTALLED
OTHER
OWNER_INSTALLED
PORT_INSTALLED
SOFTWARE_UPDATE
THIRD_PARTY_INSTALLED
UNKNOWN
}
class OptionTypes #FAFF91 {
ACCESSORY
APPEARANCE
CERTIFICATION
COLOR
EQUIPMENT
FABRIC
INCENTIVE
OTHER
PACKAGE_GOODS
PARTS
PORT_INSTALLED
REBATE_INCENTIVE
SERVICE_PLAN
SOFTWARE
SUBSCRIPTION
TELEMATICS
WARRANTY_PLAN
}
class OrderCategoryTypes #FAFF91 {
COMMERCIAL
CONTRACT
CUSTOM_ORDER
DIRECT
EDUCATIONAL
E_COMMERCE
FLEET
GOVERNMENT
LEASE
OTHER
RETAIL
STANDARD
SUBSCRIPTION
TRADE_IN
WHOLESALE
}
class PartConditionTypes #FAFF91 {
COLLECTIBLE
DAMAGED_COSMETIC
DAMAGED_MINOR
NEW
NEW_OLD_STOCK
OTHER
REBUILT
REFURBISHED
REMANUFACTURED
SALVAGE
SCRAP
USED
}
class PartyRelationshipTypes #FAFF91 {
ACCOUNTABLE
ACQUAINTANCE
ACTOR
ADVISOR
ADVISOR_CONSULTANT
AFFILIATE
AGENT
APPLICANT
ASSOCIATE
AUDITOR
BENEFICIARY
BRANCH
BUSINESS_DEVELOPMENT
BUSINESS_PARTNER
BUYER
CAREGIVER
CHILD
CLOSING_MGR
COMPOSED_IN
CONCIERGE_MGR
CONCIERGE_STAFF
CONSULT
CONTRACTOR
CORPORATION
COST_CENTER
CO_APPLICANT
CO_SIGNER
CO_WORKER
CREDIT_CARD_PROVIDER
CUSTODIAN
CUSTOMER
DEALERSHIP
DEPARTMENT
DEPENDENT
DISTRIBUTOR
DIVISION
DRIVER
EMERGENCY_CONTACT
EMPLOYEE
EMPLOYER
EXECUTE
EX_SPOUSE
FAMILY_MEMBER
FINANCE
FINANCIAL_ADVISOR
FI_MGR
FRANCHISE
FREIGHT_FORWARDER
FRIEND
GEN_MGR
GIFT_TO
GOVERNMENT_AGENCY
GROUP
GUARANTOR
HEIR
INSURED
INSURER
INTERNAL_ORGANIZATION
INVESTOR
JOINT_VENTURE
LEGAL_GUARDIAN
LESSEE
LESSOR
LIEN_HOLDER
LOAN_PROVIDER
MANAGER
MANUFACTURER
MEMBERSHIP
MENTEE
MENTOR
MERCHANT
NON_PROFIT
NOTIFY
OEM
OTHER
OTHER_FAMILY
OWNER
PARENT
PARTNER_ORGANIZATION
PART_OF
PASSENGER
PAYEE
PAYER
POLITICAL_AFFILIATE
PRIMARY_OEM
PROFESSIONAL_CONTACT
PROVIDER
PROXY
RECIPIENT
REFERENCE_PERSONAL
REFERENCE_PROFESSIONAL
REGULATOR
REMOVE
RESPONSIBLE
ROMANTIC_PARTNER
SALES_ASSOC
SALES_MGR
SECTION
SELF
SERVICE_CONSUMER
SERVICE_MGR
SERVICE_PROVIDER
SERVICE_TECH
SHAREHOLDER
SHIP_TO
SIBLING
SOLD_TO
SPECIALIST
SPOUSE
STAFF
STORE
SUBSIDIARY
SUPPLIER
TEAM
THIRD_PARTY
TRANSACTION_FROM
TRANSACTION_TO
TRUSTEE_PERSON
UNDERWRITER
VALET
VENDOR
}
class PartyTypes #FAFF91 {
CONTRACTOR
CUSTOMER
DEALER
DEVICE
DRIVER
EMPLOYEE
FINANCE
FLEET
GOVERNMENT
GROUP
ORGANIZATION
PARTNER
PERSON
PROSPECT
PUBLIC
RENTAL
RESALE
SERVICE
SUPPLIER
TAX
VENDOR
}
class PayTypes #FAFF91 {
CUSTOMER_PAY
DEALER
INTERNAL
MANUFACTURER
SUBLET
WARRANTY
}
class PaymentTypes #FAFF91 {
BALLON
CASH
CONSUMPTION_BASED
CUSTOM_AGREEMENT
DEPOSIT
FINANCED_PURCHASE
LEASE
LEASE_BUYOUT
LEASE_NO_BUYOUT
OUTRIGHT_PURCHASE
PROGRESS_PAYMENT
SCHEDULED_PAYMENT
SUBSCRIPTION
}
class PriceTypes #FAFF91 {
ACTUAL
ADJUSTED_MSRP
AFFILIATE
APPLIED_REWARD_TOTAL
BALANCE
BASE
BASE_MSRP
BUNDLE
CONTRACT
CORE
CREDIT_TOTAL
CUSTOM
CUSTOMER
DEALER_COST
DISABILITY_PREMIUM_TOTAL
DISCOUNT
DISCOUNT_PACKAGES_TOTAL
DISCOUNT_TOTAL
ESTIMATED
FEE_TOTAL
FINANCE_TOTAL
FLAT
FREIGHT_CHARGE
FUEL
GROSS_SALE
INTERNET
ITEMIZED
LANDED
LICENSED
LIST
LOCATION
METERED
MONEY
MSRP
NET
NET_SALE
NET_SALE_REDUCTION_PRICE
NONTAXABLE
ONLINE
OTHER
PERCENT
PER_UNIT
PPO_HOLD_BACK
PREMIUM_TOTAL
PRODUCT_TOTAL
PROMOTIONAL
PURCHASE
QUANTITY
REBATE_TOTAL
RECONDITIONING_COST
REGION
REMOVED_EQUIPT_TOTAL
RESIDUAL_VALUE
RETAIL
SALE
SEAT
STAIR_STEP
STANDARD
STORE
SUBSCRIPTION
TAX
TAXABLE
TAX_TOTAL
TDA
TIER_GRADUATED
TIER_VOLUME
TOTAL
TOTAL_COST
TOTAL_DEALER_COST
TOTAL_DEALER_OPTION_COST
TOTAL_DEALER_OPTION_SELLING_PRICE
TOTAL_HOLD_BACK
TOTAL_MSRP
TOTAL_OPTION_MSRP
TRADE
TRADE_IN_EQUITY_TOTAL
TRADE_IN_TOTAL
UNIT
UNIT_COST
UPFRONT_PAYMENT_TOTAL
USAGE
VOLUME
WHOLESALE
WRF
}
class ProductStateTypes #FAFF91 {
ARCHIVED
CERTIFIED
COMPANY_OWNED
CUSTOMER_OWNED
DEMO
DISCONTINUED
IN_TRANSIT
NEW
PARTNER_OWNED
REFURBISHED
RENTAL
THIRD_PARTY_OWNED
UNKNOWN
USED
}
class ProductTypes #FAFF91 {
ACCESSORY
APP
DEALER_PRODUCT
DURABLE_GOODS
EQUIPMENT
FINANCE
F_N_I_PRODUCT
INFORMATION
INSURANCE
OTHER
PACKAGE_GOODS
PART
SERVICE
SERVICE_PACKAGE
SERVICE_PLAN
SOFTWARE
SUBSCRIPTION
VEHICLE
WARRANTY_PLAN
}
class PurchaseTypes #FAFF91 {
COMMERCIAL
CONTRACT
DEMO
DIRECT
FLEET
LEASE
OTHER
RETAIL
STANDARD
WHOLESALE
}
class ResourceTypes #FAFF91 {
ACCESSORIES
ACCOUNT
ACTIVITY
ADDRESS
APPLICANT
APPOINTMENT
BILL_ADDRESS
BILL_CONTACT
COMM_CHANNEL
CUSTOMER
DEAL
DEALERSHIP
DEALER_STAFF
DISCOUNT
DRIVER
EXPENSE
FEE
FINANCE
FUNCTION
INCENTIVE
INCIDENT
INSURANCE
INVOICE
LEAD
LINEITEM
MANUFACTURER
OPPORTUNITY
OTHER
PART
PARTY
PROCESS
PRODUCT
PURCHASE_ORDER
RENTAL
SERVICE
SUBSCRIPTION
SYSTEM
TAX
TRADE_IN
VEHICLE
VEHICLE_OPTION
VENDOR
WARRANTY
WORKFLOW
}
class StaffRoleTypes #FAFF91 {
APPRAISER
BUSINESS_MANAGER
CLOSING_MANAGER
CUSTOMER_SERVICE
DETAILER
DRIVER
F_I_MANAGER
GENERAL_MANAGER
PARTS_ADVISOR
PARTS_MANAGER
RECEPTIONIST
SALES_MANAGER
SALES_PERSON
SERVICE_ADVISOR
SERVICE_MANAGER
SERVICE_TECHNICIAN
TECHNICIAN
UNKNOWN
}
class UOMLengthTypes #FAFF91 {
A
ANGSTROM
CABLE
CENTIMETER
CHAIN
CM
CUBIT
DECIMETER
DEGREE
FATHOM
FEET
FURLONG
HAND
INCH
KILOMETER
KM
LEAGUE
LINK
METER
METER_SYN
MICRON
MILE
MILES
MILLIMETER
MILLI_INCH
MM
NANOMETER
NAUTICAL_MILE
NORMAL_METRIC
PERCH
PIXEL
POLE
ROD
SPAN
VARA
YARD
YOTTAMETER
}
class UOMQuantityCategoryTypes #FAFF91 {
COUNT
DEFAULT_LEAD_TIME
DIMENSIONAL_WEIGHT
DIMENSIONS
DIMENSION_UNIT
ELECTRICAL_RATING
EXPIRATION_DATE
GROSS_VOLUME
GROSS_WEIGHT
MATERIAL
MAX_HEIGHT
MAX_LEAD_TIME
MAX_LENGTH
MAX_ORDER_QUANTITY
MAX_WEIGHT
MAX_WIDTH
MIN_HEIGHT
MIN_LENGTH
MIN_ORDER_AVAILABLE
MIN_ORDER_QUANTITY
MIN_PAYMENT_AMOUNT
MIN_PAYMENT_PERCENT
MIN_WEIGHT
MIN_WIDTH
NET_VOLUME
NET_WEIGHT
PACKAGE_QUANTITY
SHELF_LIFE_HOURS
SHIPPING_DIM_GROSS_WEIGHT
SHIPPING_DIM_HEIGHT
SHIPPING_DIM_LENGTH
SHIPPING_DIM_NET_WEIGHT
SHIPPING_DIM_WIDTH
SHIPPING_WEIGHT
TIME
VOLUME
WEIGHT
}
class VehicleBodyStyleTypes #FAFF91 {
BIKE
CARGO_VAN
COMMERCIAL_VAN
CONTRACTOR
CONVERTIBLE
COUPE
CROSSOVER
DUMP
HATCHBACK
LUXURY
MINI_VAN
OTHER
PASSENGER_VAN
SEDAN
SERVICE
SPORTS
SUV
TRUCK
UNKNOWN
VAN
WAGON
}
class VehicleCategoryTypes #FAFF91 {
CLASSIC
COMMUTER
ELECTRIC
FAMILY
FUEL_EFFICIENT
HYBRID
LARGE
LUXURY
MUSCLE
OFF_ROAD
OTHER
SMALL
SPORT
SUPERCAR
UNKNOWN
}
class VehicleHistoryEventTypes #FAFF91 {
AIRBAG_DEPLOY
COMMERCIAL_USE
CORRECTED_TITLE
FLOOD_EVENT
LEASE_USE
LEMON_TITLE
MAINT_SERVICE
MAJOR_ACCIDENT
MINOR_ACCIDENT
NEW_TITLE
ODOMETER_CHECK
ODOMETER_ROLLBACK
OTHER
OWNER_HISTORY
PERSONAL_USE
POLICE_USE
PORT_ENTRY
PRODUCTION
REBUILD
RECALL_SERVICE
RENTAL_USE
REPAIR_DAMAGE
SALE
STRUCTURAL_DAMAGE
TAXI_USE
TOTAL_LOSS
UNKNOWN
UPDATED_TITLE
}
class VehicleResourceTypes #FAFF91 {
AIRBAG
AIR_EX
AIR_FILTER
AIR_INT
AIR_METERING
BATTERY
BODY
BRAKES
BRAKE_FLUID
BRAKE_PAD
CHARGE
CHARGER
CHARGE_POWER
CHARGE_PRIORITY
CHASSIS
DIAGNOSTIC
DOOR
DRIVE_CYCLE
ELECTRICAL
EMISSION
ENERGY
ENGINE
FLUID
FUEL
GEAR
IDLE
IDLE_CONTROL
IGNITION
LAMPS
LIGHTS
MOTOR
NETWORK
ODOMETER
OIL
PLACARD
PLUG
POWER_TRAIN
RANGE
SPEED
SPEED_CONTROL
STABILITY
STARTER
SYSTEM_HW
SYSTEM_SW
TIRE
TRANSMISSION
WASHER_FLUID
}
AddressReference *-- PartyReference
AddressTypes *-- AddressReference
ApplicationStatusTypes -- CreditApplicationReference
CabTypes -- VehicleSpecification
Code *-- EffectivePeriod
Code *-- Identifier
Code *-- Insurance
Code *-- MetricValue
Code *-- Option
Code *-- PartyReference
Code *-- ProductContract
Code *-- ProductModel
Code *-- RetailDeliveryReport
Code *-- RetailDeliveryReportCriteria
Code *-- ShipmentReference
Code *-- Vehicle
Code *-- VehicleComponent
Code *-- VehicleEvent
Code *-- VehicleIdentifier
Code *-- Warranty
ColorDetail -- Vehicle
ColorDetail -- VehicleSpecification
CommunicationChannelTypes -- CommunicationChannel
CommunicationChannel *-- PartyReference
ContractStatusTypes -- ProductContract
ContractTypes *-- ProductContract
ControlAccountTypes -- Vehicle
CreditApplicationReference -- RetailDeliveryReport
CreditApplicationReference -- RetailDeliveryReportCriteria
DealStatusTypes -- RetailDeliveryReport
DealStatusTypes -- RetailDeliveryReportCriteria
DocumentReference *-- ProductContract
DocumentTypes -- DocumentReference
DurationIntervalTypes -- PaymentScheduleReference
DurationUOMTypes -- EffectivePeriod
EffectivePeriod -- PartyReference
EffectivePeriod -- PaymentScheduleReference
EffectivePeriod -- Price
EffectivePeriod -- ProductContract
EffectivePeriod -- ShipmentReference
EffectivePeriod -- VehicleEvent
EffectivePeriod -- VehicleLicense
EngineTypes *-- VehicleSpecification
EventMessageTypes -- EventMessage
EventMessage *-- RetailDeliveryReport
Feature *-- Vehicle
FuelTypes *-- VehicleEconomy
FuelTypes *-- VehicleSpecification
Identifier -- PartyReference
Identifier -- PaymentScheduleReference
Identifier -- RetailDeliveryReport
Identifier -- RetailDeliveryReportCriteria
Identifier *-- Insurance
Identifier *-- Locale
Identifier *-- ProductContract
Identifier *-- ProductModel
Identifier *-- RetailDeliveryReport
Identifier *-- RetailDeliveryReportCriteria
Identifier *-- Vehicle
Identifier *-- VehicleEvent
Identifier *-- VehicleIdentifier
Identifier *-- Warranty
InsuranceTypes -- Insurance
Insurance *-- Vehicle
InventoryStatusTypes *-- Vehicle
LeadStatusTypes -- RetailDeliveryReport
LeadStatusTypes -- RetailDeliveryReportCriteria
LeaseTerm -- RetailDeliveryReport
LifecycleEventTypes -- LifecycleEvent
LifecycleEvent *-- CreditApplicationReference
LifecyclePulseTypes *-- LifecyclePulse
LifecyclePulse *-- Manifest
Locale -- CommunicationChannel
Locale -- CreditApplicationReference
Locale -- PartyReference
Locale -- PriceSummary
Locale -- RetailDeliveryReport
Locale -- RetailDeliveryReportCriteria
ManifestItem *-- Manifest
Manifest *-- LeaseTerm
Manifest *-- RetailDeliveryReport
Manifest *-- VehicleComponent
MetricValue -- Insurance
MetricValue -- Option
MetricValue -- ProductContract
MetricValue -- RetailDeliveryReport
MetricValue -- Vehicle
MetricValue -- VehicleEconomy
MetricValue -- VehicleEvent
MetricValue -- VehicleIdentifier
MetricValue -- VehicleSpecification
MetricValue -- Warranty
MetricValue *-- VehicleComponent
NarrativeUomTypes -- MetricValue
NarrativeUomTypes -- ProductContract
OemRdrStatusTypes -- RetailDeliveryReport
OemRdrStatusTypes -- RetailDeliveryReportCriteria
OptionInstallationTypes -- Option
OptionTypes -- Option
Option *-- Vehicle
OrderCategoryTypes -- VehiclePriceSummary
PartConditionTypes -- Vehicle
PartyReference -- Insurance
PartyReference -- ShipmentReference
PartyReference *-- CreditApplicationReference
PartyReference *-- ProductContract
PartyReference *-- RetailDeliveryReport
PartyReference *-- RetailDeliveryReportCriteria
PartyRelationshipTypes *-- PartyReference
PartyTypes -- RetailDeliveryReport
PartyTypes -- RetailDeliveryReportCriteria
PayTypes -- Price
PaymentScheduleReference -- ProductContract
PaymentTypes -- VehiclePriceSummary
PersonName -- PartyReference
Position -- Vehicle
Position -- VehicleEvent
Price -- LeaseTerm
Price -- VehiclePriceSummary
PriceSummary -- CreditApplicationReference
PriceSummary -- Insurance
PriceSummary -- Option
PriceSummary -- ProductContract
PriceSummary -- Vehicle
PriceTypes *-- Price
Price *-- PriceSummary
ProductContract *-- RetailDeliveryReport
ProductModel -- VehicleIdentifier
ProductStateTypes *-- Vehicle
ProductStateTypes -- RetailDeliveryReport
ProductStateTypes -- RetailDeliveryReportCriteria
ProductTypes *-- Option
PurchaseTypes -- RetailDeliveryReport
PurchaseTypes -- RetailDeliveryReportCriteria
ResourceTypes -- LifecycleEvent
ResourceTypes -- PriceSummary
RetailDeliveryReportCriteria -- RetailDeliveryReport
ShipmentReference -- RetailDeliveryReport
StaffRoleTypes -- EventMessage
UOMLengthTypes -- LeaseTerm
UOMQuantityCategoryTypes -- UnitOfMeasure
UnitOfMeasure *-- ShipmentReference
Vehicle -- RetailDeliveryReport
VehicleBodyStyleTypes *-- VehicleSpecification
VehicleCategoryTypes *-- VehicleSpecification
VehicleComponent *-- Vehicle
VehicleEconomy *-- Vehicle
VehicleEconomy *-- VehicleSpecification
VehicleEvent *-- Vehicle
VehicleHistoryEventTypes -- Vehicle
VehicleHistoryEventTypes -- VehicleEvent
VehicleIdentifier -- Insurance
VehicleIdentifier -- RetailDeliveryReport
VehicleIdentifier -- RetailDeliveryReportCriteria
VehicleIdentifier -- Vehicle
VehicleLicense -- VehicleIdentifier
VehiclePriceSummary *-- Vehicle
VehiclePriceSummary -- Vehicle
VehicleResourceTypes *-- VehicleSpecification
VehicleResourceTypes -- VehicleComponent
VehicleSpecification -- Vehicle
Warranty *-- Vehicle
@enduml
