@startuml
class ActorReference {
actorReferenceId:String
actorReferenceKey:String
actorKey:String
actorName:String
actorType:ActorTypes
actorHref:String
occurrenceDateTime:Date
}
class AddressReference {
addressReferenceKey:String
addressReferenceId:String
addressLine1:String
addressLine2:String
addressLine3:String
addressLine4:String
addressLine5:String
city:String
countryCode:String
district:String
label:String
postalCode:String
stateProvince:String
}
class AuthorizationLevel {
updateDateTime:Date
authorizedIndicator:Boolean
authorizationLevelKey:String
}
class CommunicationChannel {
communicationChannelKey:String
communicationChannelId:String
communicationChannelType:CommunicationChannelTypes
value:String
verifiedIndicator:Boolean
valueExtension:String
label:String
locale:Locale
preferredIndicator:Boolean
preferences:List<TimeSlot>
authorizationLevels:List<AuthorizationLevel>
}
class ControlAccountReference {
controlAccountReferenceId:String
controlAccountReferenceKey:String
controlAccountKey:String
context:String
occurrenceDateTime:Date
}
class CreditReference {
creditReferenceId:String
creditReferenceKey:String
creditKey:String
context:String
occurrenceDateTime:Date
sequenceId:String
taxableIndicator:Boolean
}
class CurrencyExchange {
currencyExchangeId:String
currencyExchangeKey:String
sourceCurrency:String
targetCurrency:String
currencyExchangeDesc:String
exchangeRate:String
rateDateTime:Date
}
class DeliveryProfile {
deliveryProfileKey:String
deliveryProfileId:String
deliveryDestinationType:DeliveryDestinationTypes
fulfillmentMethodType:FulfillmentMethodTypes
serviceLevelType:ServiceLevelTypes
deliveryProfileName:String
deliveryStateType:ShipmentStateTypes
deliveryMethodTypes:List<ShippingMethodTypes>
deliveryPriorityType:String
deliveryWindow:String
deliveryPeriod:EffectivePeriod
deliveryContact:PartyReference
deliveryAddress:AddressReference
deliveryInstructions:String
contactlessDeliveryIndicator:Boolean
signatureRequiredIndicator:Boolean
appointmentRequiredIndicator:Boolean
residentialDeliveryIndicator:Boolean
loadingDockIndicator:Boolean
afterHoursDeliveryIndicator:Boolean
deliverySource:String
comments:String
}
class DiscountMetricValue {
discountMetricValueKey:String
unitOfMeasureType:UnitOfMeasureTypes
value:String
}
class DiscountReference {
discountReferenceId:String
discountReferenceKey:String
discountKey:String
unitCount:String
context:String
occurrenceDateTime:Date
sequenceId:String
taxableIndicator:Boolean
discountPlanName:String
discountDuration:EffectivePeriod
discountHref:String
discountMetricValues:List<DiscountMetricValue>
discountPrice:Price
capitalizedIndicator:Boolean
purchaseTypes:List<OrderCategoryTypes>
productStateTypes:List<ProductStateTypes>
}
class EffectivePeriod {
effectivePeriodKey:String
activeIndicator:Boolean
exclusiveIndicator:Boolean
startDateTime:Date
completeDateTime:Date
durationUomType:DurationUomTypes
durationValue:String
recurUomType:DurationUomTypes
recurCount:String
recurCriteria:String
recurIndicator:Boolean
}
class FeeReference {
feeReferenceId:String
feeReferenceKey:String
feeKey:String
unitCount:String
context:String
occurrenceDateTime:Date
sequenceId:String
taxableIndicator:Boolean
}
class FinancialCategoryReference {
categoryReferenceId:String
categoryReferenceKey:String
categoryKey:String
context:String
occurrenceDateTime:Date
}
class FinancialEvent {
financialEventId:String
financialEventKey:String
confirmationCode:String
forecastIndicator:Boolean
paymentMethodType:PaymentMethodTypes
paymentMethodKey:String
occurrenceDateTime:Date
postDate:Date
transactionDate:Date
batchNumber:String
previousEventTypes:List<PaymentTransactionStatusTypes>
providerTransactionId:String
eventDescription:String
financialEventType:FinancialEventTypes
resourceType:ResourceTypes
ledgerActionType:LedgerActionTypes
resourceId:String
correlationId:String
causationId:String
trackingRef:String
sourceTransactionId:String
amount:GeneralAmount
depositType:DepositTypes
controlAccountReference:ControlAccountReference
actor:ActorReference
financialCategories:List<FinancialCategoryTypes>
sourceSystemCode:String
}
class FinancialSplit {
financialSplitId:String
financialSplitKey:String
sourceItemKey:String
priceName:String
priceDescription:String
amount:GeneralAmount
controlAccountReference:ControlAccountReference
financialCategories:List<FinancialCategoryReference>
ledgerActionType:LedgerActionTypes
ledgerTypes:FinancialTransactionTypes
priceType:ProductPriceItemTypes
taxSplits:List<TaxSplit>
rewardReferences:List<RewardReference>
creditReferences:List<CreditReference>
rebateReferences:List<RebateReference>
discountReferences:List<DiscountReference>
feeReferences:List<FeeReference>
parties:List<PartyReference>
payType:PayTypes
}
class FinancialTrack {
financialTrackId:String
financialTrackKey:String
referenceKey:String
occurrenceDateTime:Date
actorId:String
financialSplits:List<FinancialSplit>
}
class FleetReference {
fleetReferenceKey:String
fleetKey:String
fleetId:String
fleetNumber:String
fleetName:String
parentFleetKey:String
parentFleetName:String
fleetTypes:List<PartyTypes>
displayName:String
}
class FulfillmentProfile {
fulfillmentProfileId:String
fulfillmentProfileKey:String
fulfillmentMethodType:FulfillmentMethodTypes
orderTypes:List<OrderTypes>
fulfillmentStatusType:FulfillmentStatusTypes
serviceLevelType:ServiceLevelTypes
deliveryDestinationType:DeliveryDestinationTypes
destinationPartyReference:PartyReference
destinationAddressReference:AddressReference
pickupPartyReference:PartyReference
pickupAddressReference:AddressReference
fulfillmentPeriod:EffectivePeriod
shipmentProfiles:List<ShipmentProfile>
comments:String
}
class GeneralAmount {
generalAmountKey:String
currencyCode:String
value:String
}
class InvoiceReference {
invoiceReferenceId:String
invoiceReferenceKey:String
invoiceKey:String
context:String
occurrenceDateTime:Date
invoiceType:InvoiceTypes
}
class Locale {
localeKey:String
localeName:String
description:String
languageCode:String
countryCode:String
currencyCode:String
currencySymbol:String
timezone:String
numberFormat:String
locationCode:String
}
class MetricValue {
metricValueId:String
metricValueKey:String
value:String
uom:NarrativeUomTypes
}
class Money {
moneyKey:String
moneyId:String
currencyCode:String
displayValue:String
locale:String
amount:GeneralAmount
currencyExchange:CurrencyExchange
}
class OptionDescription {
optionDescriptionKey:String
optionDescriptionId:String
optionDescriptionGroup:String
optionDescriptionLabel:String
}
class PartIdentifierReference {
partIdentifierReferenceKey:String
partIdentifierReferenceId:String
partNumber:String
manufacturerBrandCode:String
descriptionSnapshot:String
itemClassificationType:PartInvoiceItemTypes
}
class PartyReference {
partyReferenceId:String
partyReferenceKey:String
partyKey:String
partyName:String
individualName:PersonName
partyType:PartyTypes
authorizationCode:String
sourceSystemCode:String
context:String
accountNumber:String
partyRelationshipTypes:List<PartyRelationshipTypes>
addressReferences:List<AddressReference>
communicationChannels:List<CommunicationChannel>
occurrenceDateTime:Date
orgIndicator:Boolean
}
class PersonName {
alias:String
familyName:String
fullName:String
givenName:String
identifiersHref:String
maidenName:String
middleName:String
nameSuffix:String
partyKey:String
personKey:String
personNameKey:String
personNameId:String
preferredName:String
salutation:String
honorificPrefix:String
honorificSuffix:String
locale:String
phoneticFamilyName:String
phoneticGivenName:String
phoneticMiddleName:String
nationality:String
}
class Position {
positionId:String
positionKey:String
latitude:String
longitude:String
altitude:String
bearing:String
postalCode:String
countyCode:String
}
class Price {
priceKey:String
displayValue:String
value:Money
taxValue:Money
taxableAmount:Money
nonTaxableAmount:Money
totalAmount:Money
totalCostAmount:Money
unitCostAmount:Money
priceDescription:String
taxIncludedIndicator:Boolean
currencyCode:String
priceId:String
duration:EffectivePeriod
priceTypes:List<PriceTypes>
payType:PayTypes
}
class RebateReference {
rebateReferenceId:String
rebateReferenceKey:String
rebateKey:String
context:String
occurrenceDateTime:Date
sequenceId:String
taxableIndicator:Boolean
rebateName:String
rebatePrice:Price
capitalizedIndicator:Boolean
purchaseType:OrderCategoryTypes
paymentTypes:List<PaymentTypes>
productStateType:ProductStateTypes
locationCode:String
incentiveType:IncentiveTypes
rebateDuration:EffectivePeriod
rebateHref:String
}
class RewardReference {
rewardReferenceId:String
rewardReferenceKey:String
rewardKey:String
context:String
occurrenceDateTime:Date
sequenceId:String
taxableIndicator:Boolean
}
class ShipmentEvent {
shipmentEventKey:String
shipmentEventId:String
shipmentEventType:String
shipmentStateType:ShipmentStateTypes
previousShipmentStateType:ShipmentStateTypes
location:Position
occurrenceDateTime:Date
recordedDateTime:Date
effectiveDateTime:Date
eventSource:String
description:String
}
class ShipmentManifestLine {
shipmentManifestLineKey:String
shipmentManifestLineId:String
partInvoiceItemId:String
context:String
occurrenceDateTime:Date
quantityShipped:String
unitOfMeasure:UnitOfMeasure
manifestLineWeight:MetricValue
partConditionType:PartConditionTypes
partIdentifierReference:PartIdentifierReference
containerReferenceId:String
}
class ShipmentProfile {
shipmentProfileKey:String
shipmentProfileId:String
referenceKey:String
caseNumber:String
shipmentStateType:ShipmentStateTypes
shipmentPriorityType:String
shippingMethodTypes:List<ShippingMethodTypes>
shippingCarriers:List<PartyReference>
shipFromParty:PartyReference
shipToParty:PartyReference
shipFromAddress:AddressReference
shipToAddress:AddressReference
countryOfOrigin:String
billOfLadingNumber:String
packingSlipNumber:String
trackingInformations:List<TrackingInformation>
shipmentEvents:List<ShipmentEvent>
shipmentPeriod:EffectivePeriod
shipmentManifestLines:List<ShipmentManifestLine>
invoiceReferences:List<InvoiceReference>
vehicleReference:VehicleReference
fleetReference:FleetReference
shipmentWeight:MetricValue
packageCount:Integer
signatureRequiredIndicator:Boolean
hazardousMaterialIndicator:Boolean
shipmentSource:String
comments:String
serviceLevelType:ServiceLevelTypes
transportMethodTypes:List<TransportMethodTypes>
deliveryProfile:DeliveryProfile
}
class ShipmentReference {
shipmentReferenceId:String
shipmentReferenceKey:String
shipmentKey:String
trackingNumber:String
context:String
carrierParty:PartyReference
occurrenceDateTime:Date
unitOfMeasures:List<UnitOfMeasure>
estimatedDeliveryPeriod:EffectivePeriod
shipmentStateType:ShipmentStateTypes
carrierName:String
carrierTrackingUrl:String
shipFromParty:PartyReference
shipToParty:PartyReference
serviceLevelType:ServiceLevelTypes
}
class StatusTransitionEvent {
statusTransitionEventId:String
statusTransitionEventKey:String
aggregateRootType:ResourceTypes
aggregateRootKey:String
aggregateRootId:String
entityType:ResourceTypes
entityKey:String
entityId:String
stateMachineType:String
fromStatus:String
toStatus:String
trigger:String
action:String
capabilityKey:String
intentName:String
ruleSetKey:String
consequenceKey:String
guardPassedIndicator:Boolean
reasonCode:String
reasonDescription:String
actorId:String
actorType:PartyTypes
occurrenceDateTime:Date
correlationId:String
causationId:String
}
class TaxSplit {
taxSplitId:String
taxSplitKey:String
taxCode:String
taxRate:String
jurisdiction:String
taxAmount:GeneralAmount
taxType:TaxTypes
sequenceId:String
taxableIndicator:Boolean
}
class TextualDetail {
textualDetailKey:String
textualDetailId:String
shortDescription:String
textKey:String
name:String
value:String
label:String
altText:String
textualDetailCode:String
uomDisplay:String
uomCode:String
}
class TimeSlot {
timeSlotKey:String
endDay:DayOfWeekTypes
endTime:String
recurringIndicator:Boolean
recurringPeriod:EffectivePeriod
startDay:DayOfWeekTypes
startTime:String
timeslotDirectiveTypes:List<TimeslotDirectiveTypes>
timeSlotId:String
}
class TrackingInformation {
trackingInformationKey:String
trackingInformationId:String
trackingNumber:String
trackingDateTime:Date
shipmentStateType:ShipmentStateTypes
statusDescription:String
currentLocation:Position
shipmentEvents:List<ShipmentEvent>
notes:String
carrierName:String
carrierTrackingUrl:String
estimatedDeliveryDateTime:Date
actualDeliveryDateTime:Date
lastUpdatedDateTime:Date
deliveryExceptionIndicator:Boolean
exceptionReason:String
previousShipmentStateType:ShipmentStateTypes
eventSource:String
eventSequenceNum:String
exceptionSeverityType:ExceptionSeverityTypes
}
class UnitOfMeasure {
unitOfMeasureKey:String
unitName:String
uomValue:String
uomQuantityCategoryType:UomQuantityCategoryTypes
}
class VehicleInvoice {
vehicleInvoiceId:String
vehicleInvoiceKey:String
invoiceNumber:String
correlationId:String
invoiceType:InvoiceTypes
vehicleReferences:List<VehicleReference>
partyReferences:List<PartyReference>
customerReference:PartyReference
invoiceDateTime:Date
processDateTime:Date
vehicleInvoiceItems:List<VehicleInvoiceItem>
totals:List<FinancialSplit>
fulfillmentProfile:FulfillmentProfile
financialEvents:List<FinancialEvent>
financialTracks:List<FinancialTrack>
statusTransitionEvents:List<StatusTransitionEvent>
invoiceStatusType:InvoiceStatusTypes
paymentStatusType:PaymentStatusTypes
controlAccountReference:ControlAccountReference
}
class VehicleInvoiceItem {
vehicleInvoiceItemId:String
vehicleInvoiceItemKey:String
lineNumber:String
vehicleInvoiceItemType:VehicleInvoiceItemTypes
vehicleOptions:List<VehicleOption>
itemCode:String
description:List<TextualDetail>
msrpPrice:Price
invoicePrice:Price
noChargeIndicator:Boolean
includedIndicator:Boolean
priceType:ProductPriceItemTypes
vehicleReference:VehicleReference
totals:List<FinancialSplit>
fulfillmentProfile:FulfillmentProfile
shipmentReferences:List<ShipmentReference>
}
class VehicleOption {
vehicleOptionKey:String
invoicePrice:Price
manufacturerName:String
optionCode:String
optionDescriptions:List<OptionDescription>
optionInstallationType:OptionInstallationTypes
optionName:String
optionType:OptionTypes
quantity:MetricValue
retailPrice:Price
shortDescription:String
}
class VehicleReference {
vehicleReferenceKey:String
vehicleReferenceId:String
vehicleIdentifierKey:String
vin:String
modelYear:String
make:String
model:String
trim:String
displayName:String
stockNumber:String
licensePlate:String
dealerCode:String
}
class ActorTypes #FAFF91 {
AGENT
AI_AGENT
API
APPLICATION
CONTRACTOR
CUSTOMER
DEALER
DEVICE
EMPLOYEE
EVENT_HANDLER
GOVERNMENT
ORGANIZATION
PARTNER
PROCESS
RULE_ENGINE
SCHEDULER
SENSOR
SERVICE
SUPPLIER
SYSTEM
UNKNOWN
USER
VENDOR
WORKFLOW
}
class AddressTypes #FAFF91 {
ARCHIVE
AR_ADDRESS
BILLING
BUSINESS
CONTRACT
CONVOY
CURRENT
DEALER
DELIVERY
DESTINATION
EMERGENCY
GARAGE
HOME
HUB
INSURANCE
LEGAL
MAILING
OFFICE
ORIGINAL
OTHER
PORT
POSTAL
PO_BOX
PREVIOUS
PRODUCT
RAIL
RAMP
REBATE
RECIPIENT
RESIDENCE
SERVICE
SERVICE_CONTRACT
SHIPPING
TEMPORARY
VACATION
WORK
}
class CommunicationChannelTypes #FAFF91 {
APP
BROADCAST
CELL
DIRECT_MAIL
EMAIL
OTHER
PDA
PHONE
SMS
SOCIAL_MEDIA
URL
VIDEO
VOICE
}
class DayOfWeekTypes #FAFF91 {
FRI
MON
SAT
SUN
THURS
TUES
WED
}
class DeliveryDestinationTypes #FAFF91 {
AUCTION
BODY_SHOP
CUSTOMER
DEALERSHIP
FLEET_LOCATION
LOCKER
OEM
OTHER
PORT
SERVICE_CENTER
TECHNICIAN
UNKNOWN
VENDOR
WAREHOUSE
}
class DepositTypes #FAFF91 {
CUSTOMER_DEPOSIT
DAMAGE_DEPOSIT
DOWN_PAYMENT
ESCROW_DEPOSIT
FLEET_ORDER_DEPOSIT
GOOD_FAITH_DEPOSIT
LEASE_SECURITY_DEPOSIT
NON_REFUNDABLE_DEPOSIT
OTHER
PARTS_DEPOSIT
REFUNDABLE_DEPOSIT
RESERVATION_DEPOSIT
SECURITY_DEPOSIT
SERVICE_DEPOSIT
SPECIAL_ORDER_DEPOSIT
TRADE_HOLD_DEPOSIT
VEHICLE_HOLD_DEPOSIT
WHOLESALE_DEPOSIT
}
class DurationUomTypes #FAFF91 {
BI_WEEKS
CUSTOM
DAYS
DAY_OF_MONTH
HOURS
MINUTES
MONTHS
MULTI_YEARS
NONE
OCCURRENCE
OTHER
QUARTERS
SEMI_MONTHS
SEMI_YEARS
UNLIMITED
WEEKS
YEARS
}
class ExceptionSeverityTypes #FAFF91 {
BLOCKING
COMPLIANCE
CRITICAL
DAMAGED
EMERGENCY
FAILED
INFORMATIONAL
LOST
MAJOR
MINOR
MODERATE
NOTICE
OTHER
SECURITY
UNKNOWN
WARNING
}
class FinancialCategoryTypes #FAFF91 {
ADJUSTMENT
CAPEX
CHARGEBACK
CREDIT
DEPOSIT
FEE
FINANCE_CONTRACT
HARDWARE
JOURNAL_ENTRY
MAINTENANCE
OPEX
OTHER
PARTS_INVOICE
PAYMENT
REFUND
RENT
REVENUE
SALARY
SERVICE_INVOICE
SOFTWARE
TAX
TRAINING
TRAVEL
UTILITIES
VEHICLE_INVOICE
WRITE_OFF
}
class FinancialEventTypes #FAFF91 {
ADJUSTMENT_APPLIED
ADJUSTMENT_CREATED
ADJUSTMENT_REVERSED
CHARGEBACK_RECEIVED
CHARGEBACK_REVERSED
CREDIT_APPLIED
CREDIT_EXPIRED
CREDIT_ISSUED
CREDIT_REVERSED
DEPOSIT_APPLIED
DEPOSIT_CREATED
DEPOSIT_FORFEITED
DEPOSIT_RECEIVED
DEPOSIT_REFUNDED
DEPOSIT_TRANSFERRED
DEPOSIT_VOIDED
FEE_ASSESSED
FEE_REFUNDED
FEE_REVERSED
FEE_WAIVED
FINANCE_CONTRACT_CANCELLED
FINANCE_CONTRACT_CREATED
FINANCE_CONTRACT_FUNDED
INVOICE_CANCELLED
INVOICE_CREATED
INVOICE_ISSUED
INVOICE_POSTED
INVOICE_VOIDED
JOURNAL_ENTRY_CREATED
JOURNAL_ENTRY_POSTED
JOURNAL_ENTRY_REVERSED
PAYMENT_APPLIED
PAYMENT_CREATED
PAYMENT_FAILED
PAYMENT_RECEIVED
PAYMENT_REVERSED
PAYMENT_UNAPPLIED
PAYMENT_VOIDED
REFUND_CANCELLED
REFUND_COMPLETED
REFUND_CREATED
REFUND_ISSUED
REFUND_REVERSED
TAX_ADJUSTED
TAX_ASSESSED
TAX_REFUNDED
WRITE_OFF_CREATED
}
class FinancialTransactionTypes #FAFF91 {
ACCRUED_EXPENSE
AMORTIZATION
ASSETS
BANK_CHARGE
CAPITALIZATION
CASH_INFLOW
CASH_OUTFLOW
COGS
CONTRA_ASSET
CREDIT
CUSTOM
DEBIT
DEFERRED_REVENUE
DEPRECIATION
DISBURSEMENT
DIVIDEND
EQUITY
EXPENSE
FEE
INCOME
INTANGIBLE_ASSET
INTEREST_EXPENSE
INTEREST_INCOME
INVENTORY
INVESTMENT
INVOICE
LIABILITY
LOAN_PAYABLE
LOAN_RECEIVABLE
OBLIGATION_CREDIT
OBLIGATION_NOTE
OBLIGATION_OTHER
OBLIGATION_TAX
OTHER
PREPAID_EXPENSE
PROVISION
REBATE
RECEIPT
RECEIVABLE_RECEIPT
RETURNS
SALES_DISCOUNT
SERVICE
TAX_PAYABLE
TRANSFER
VARIANCE
}
class FulfillmentMethodTypes #FAFF91 {
DELIVERY
DROP_SHIP
PICKUP
TRANSFER
}
class FulfillmentStatusTypes #FAFF91 {
ALLOCATED
BACKORDERED
CANCELLED
CLOSED
COMPLETED
DELIVERED
DROP_SHIP_IN_PROGRESS
EXCEPTION
FAILED
IN_TRANSIT
NOT_REQUIRED
ON_HOLD
OTHER
PACKED
PACKING
PENDING
PICKED
PICKED_UP
PICKING
READY_FOR_PICKUP
READY_FOR_SHIPMENT
RESERVED
RETURNED
RETURN_IN_PROGRESS
RETURN_REQUESTED
SHIPPED
SPECIAL_ORDERED
TRANSFER_IN_PROGRESS
WAITING_FOR_INVENTORY
}
class IncentiveTypes #FAFF91 {
DEALER
OEM
OTHER
SUPPLIER
VENDOR
}
class InvoiceStatusTypes #FAFF91 {
ACKNOWLEDGED
ADJUSTED
CANCELLED
CLOSED
DECLINED
DISPUTED
DRAFT
ISSUED
OTHER
PENDING_APPROVAL
VOIDED
}
class InvoiceTypes #FAFF91 {
ADVANCE
COMMERCIAL
CREDIT_MEMO
DEBIT_MEMO
FINAL
FINANCE_CHARGE
FUEL
INSURANCE_CLAIM
INVOICE
LEASE
LOAN
PARTS
PART_INVOICE
PRO_FORMA
RENTAL
REPAIR
SERVICE
SERVICE_INVOICE
STANDARD
STATEMENT
SUBSCRIPTION
VEHICLE_INVOICE
VEHICLE_SALE
WARRANTY_CLAIM
}
class LedgerActionTypes #FAFF91 {
CREDIT
CUSTOM
DEBIT
MEMO
NONE
OTHER
REVERSAL
TRANSFER
}
class NarrativeUomTypes #FAFF91 {
AMPERE
ARRAY
BAR
BINARY
BI_WEEKS
BOOLEAN
CELSIUS
CENTIMETER
CODE
CUBIC_METER
CURRENCY
CUSTOM
DATE
DATE_TIME
DAYS
DAY_OF_MONTH
DEGREES
DESC
DOUBLE
DURATION
FAHRENHEIT
FATHOM
FEET
FLOAT
FLUID_OUNCE
GALLON
GRAMS
GROUP
G_FORCE
HOURS
HP
INCH
INT32
INT64
INTEGER
KELVIN
KEY
KG
KILOWATT_HOUR
KM
KPA
LABEL
LB
LITER
METER
MI
MILES
MILLIMETER
MINUTES
MONTHS
MULTI_YEARS
NAUTICAL
NONE
NUMBER
OBJECT
OCCURRENCE
OHM
OTHER
OZ
PERCENT
POINTS
PROTECTED_TEXT
PSI
QUARTERS
RANKINE
RPM
SECONDS
SEMI_MONTHS
SEMI_YEARS
STRING
TEXT
TIME
TONS
UNLIMITED
VOLT
WATT
WEEKS
YARD
YEARS
}
class OptionInstallationTypes #FAFF91 {
ACCESSORY_KIT
CUSTOM_FABRICATION
DEALER_INSTALLED
FACTORY_INSTALLED
OTHER
OWNER_INSTALLED
PORT_INSTALLED
SOFTWARE_UPDATE
THIRD_PARTY_INSTALLED
UNKNOWN
}
class OptionTypes #FAFF91 {
ACCESSORY
APPEARANCE
CERTIFICATION
COLOR
EQUIPMENT
FABRIC
INCENTIVE
OTHER
PACKAGE_GOODS
PARTS
PORT_INSTALLED
REBATE_INCENTIVE
SERVICE_PLAN
SOFTWARE
SUBSCRIPTION
TELEMATICS
WARRANTY_PLAN
}
class OrderCategoryTypes #FAFF91 {
COMMERCIAL
CONTRACT
CUSTOM_ORDER
DIRECT
EDUCATIONAL
E_COMMERCE
FLEET
GOVERNMENT
LEASE
OTHER
RETAIL
STANDARD
SUBSCRIPTION
TRADE_IN
WHOLESALE
}
class OrderTypes #FAFF91 {
BACK_ORDER
CONSIGNMENT
INTERNAL_TRANSFER
JOB
MAINTENANCE
PURCHASE
RENTAL
REPAIR
RETURN
RUSH
SALES
SAMPLE
SERVICE
SPECIAL
STANDARD
SUBSCRIPTION
TRIAL
WARRANTY
}
class PartConditionTypes #FAFF91 {
COLLECTIBLE
DAMAGED_COSMETIC
DAMAGED_MINOR
NEW
NEW_OLD_STOCK
OTHER
REBUILT
REFURBISHED
REMANUFACTURED
SALVAGE
SCRAP
USED
}
class PartInvoiceItemTypes #FAFF91 {
ASSEMBLY
COMPONENT
EXCHANGE_LINE
KIT
OTHER
RETURN_LINE
STANDARD_CATALOG_PART
}
class PartyRelationshipTypes #FAFF91 {
ACCOUNTABLE
ACQUAINTANCE
ACTOR
ADVISOR
ADVISOR_CONSULTANT
AFFILIATE
AGENT
APPLICANT
ASSOCIATE
AUDITOR
BENEFICIARY
BRANCH
BUSINESS_DEVELOPMENT
BUSINESS_PARTNER
BUYER
CAREGIVER
CHILD
CLOSING_MGR
COMPOSED_IN
CONCIERGE_MGR
CONCIERGE_STAFF
CONSULT
CONTRACTOR
CORPORATION
COST_CENTER
CO_APPLICANT
CO_SIGNER
CO_WORKER
CREDIT_CARD_PROVIDER
CUSTODIAN
CUSTOMER
DEALERSHIP
DEPARTMENT
DEPENDENT
DISTRIBUTOR
DIVISION
DRIVER
EMERGENCY_CONTACT
EMPLOYEE
EMPLOYER
EXECUTE
EX_SPOUSE
FAMILY_MEMBER
FINANCE
FINANCIAL_ADVISOR
FI_MGR
FRANCHISE
FREIGHT_FORWARDER
FRIEND
GEN_MGR
GIFT_TO
GOVERNMENT_AGENCY
GROUP
GUARANTOR
HEIR
INSURED
INSURER
INTERNAL_ORGANIZATION
INVESTOR
JOINT_VENTURE
LEGAL_GUARDIAN
LESSEE
LESSOR
LIEN_HOLDER
LOAN_PROVIDER
MANAGER
MANUFACTURER
MEMBERSHIP
MENTEE
MENTOR
MERCHANT
NON_PROFIT
NOTIFY
OEM
OTHER
OTHER_FAMILY
OWNER
PARENT
PARTNER_ORGANIZATION
PART_OF
PASSENGER
PAYEE
PAYER
POLITICAL_AFFILIATE
PRIMARY_OEM
PROFESSIONAL_CONTACT
PROVIDER
PROXY
RECIPIENT
REFERENCE_PERSONAL
REFERENCE_PROFESSIONAL
REGULATOR
REMOVE
RESPONSIBLE
ROMANTIC_PARTNER
SALES_ASSOC
SALES_MGR
SECTION
SELF
SERVICE_CONSUMER
SERVICE_MGR
SERVICE_PROVIDER
SERVICE_TECH
SHAREHOLDER
SHIP_TO
SIBLING
SOLD_TO
SPECIALIST
SPOUSE
STAFF
STORE
SUBSIDIARY
SUPPLIER
TEAM
THIRD_PARTY
TRANSACTION_FROM
TRANSACTION_TO
TRUSTEE_PERSON
UNDERWRITER
VALET
VENDOR
}
class PartyTypes #FAFF91 {
CONTRACTOR
CUSTOMER
DEALER
DEVICE
DRIVER
EMPLOYEE
FINANCE
FLEET
GOVERNMENT
GROUP
ORGANIZATION
PARTNER
PERSON
PROSPECT
PUBLIC
RENTAL
RESALE
SERVICE
SHIP_TO
SOLD_TO
SUPPLIER
TAX
VENDOR
}
class PayTypes #FAFF91 {
CUSTOMER_PAY
DEALER
INTERNAL
MANUFACTURER
SUBLET
WARRANTY
}
class PaymentMethodTypes #FAFF91 {
ACH
CASH
CASH_ON_DELIVERY
CHECK
CREDIT_CARD
CRYPTOCURRENCY
DEBIT_CARD
DIGITAL_WALLET
DUE_ON_RECEIPT
EFT
EXCHANGE
FINANCE
FINANCING
GIFT_CARD
INTERNAL_CREDIT
LEASE
MOBILE_WALLET
MONEY_ORDER
NOT_APPLICABLE
ONLINE_BANK_TRANSFER
ONLINE_PAYMENT_PLATFORM
OTHER
PAYROLL_DEDUCTION
RENTAL
REWARD_POINTS
STORE_CREDIT
TERMS
TRADE_IN
UNKNOWN
WIRE_TRANSFER
}
class PaymentStatusTypes #FAFF91 {
AUTHORIZED
CHARGEBACK
FAILED
NOT_REQUIRED
OTHER
OVERDUE
PAID
PARTIALLY_PAID
PARTIALLY_REFUNDED
PENDING_PAYMENT
PENDING_SETTLEMENT
REFUNDED
SETTLED
WRITTEN_OFF
}
class PaymentTransactionStatusTypes #FAFF91 {
ACTIVATED
ADMIN_HOLD
APPROVE
AUTHORIZE
CANCEL
CAPTURED
CLOSE
CONFIRM
CONFIRMATION
CUSTOM_CODE
DEACTIVATE
DECLINE
DOWNGRADE
DUE
EXPIRED
HOLD_ON_DATE
HOLD_ON_RENEWAL
INCURRED
NONE
OPEN
OVERRIDE
PARTIALLY_REFUNDED
PAYMENT
PEND
PENDING_MERCHANT
PROCESS
REFUNDED
SUBSCRIPTION
SUSPENDED
TRIAL
UPGRADE
USER_HOLD
VOID
}
class PaymentTypes #FAFF91 {
BALLON
CASH
CONSUMPTION_BASED
CUSTOM_AGREEMENT
DEPOSIT
FINANCED_PURCHASE
LEASE
LEASE_BUYOUT
LEASE_NO_BUYOUT
OUTRIGHT_PURCHASE
PROGRESS_PAYMENT
SCHEDULED_PAYMENT
SUBSCRIPTION
}
class PriceTypes #FAFF91 {
ACTUAL
ADJUSTED_MSRP
AFFILIATE
APPLIED_REWARD_TOTAL
BALANCE
BASE
BASE_MSRP
BUNDLE
CONTRACT
CORE
CREDIT_TOTAL
CUSTOM
CUSTOMER
DEALER_COST
DISABILITY_PREMIUM_TOTAL
DISCOUNT
DISCOUNT_PACKAGES_TOTAL
DISCOUNT_TOTAL
ESTIMATED
FEE_TOTAL
FINANCE_TOTAL
FLAT
FREIGHT_CHARGE
FUEL
GROSS_SALE
INTERNET
ITEMIZED
LANDED
LICENSED
LIST
LOCATION
METERED
MONEY
MSRP
NET
NET_SALE
NET_SALE_REDUCTION_PRICE
NONTAXABLE
ONLINE
OTHER
PERCENT
PER_UNIT
PPO_HOLD_BACK
PREMIUM_TOTAL
PRODUCT_TOTAL
PROMOTIONAL
PURCHASE
QUANTITY
REBATE_TOTAL
RECONDITIONING_COST
REGION
REMOVED_EQUIPT_TOTAL
RESIDUAL_VALUE
RETAIL
SALE
SEAT
STAIR_STEP
STANDARD
STORE
SUBSCRIPTION
TAX
TAXABLE
TAX_TOTAL
TDA
TIER_GRADUATED
TIER_VOLUME
TOTAL
TOTAL_COST
TOTAL_DEALER_COST
TOTAL_DEALER_OPTION_COST
TOTAL_DEALER_OPTION_SELLING_PRICE
TOTAL_HOLD_BACK
TOTAL_MSRP
TOTAL_OPTION_MSRP
TRADE
TRADE_IN_EQUITY_TOTAL
TRADE_IN_TOTAL
UNIT
UNIT_COST
UPFRONT_PAYMENT_TOTAL
USAGE
VOLUME
WHOLESALE
WRF
}
class ProductPriceItemTypes #FAFF91 {
CREDIT
DEPOSIT_PAID
DISCOUNT
FEE
FREIGHT
FREIGHT_CHARGE
FUEL
GRAND_TOTAL
INVOICED
ITEMS
NET
ORDERED
OTHER
OUTSTANDING
PACKAGING
PAID
PPO_HOLD_BACK
PRODUCT
REBATE
REWARD
SERVICE
SERVICE_CHARGE
SHIPPING_AND_HANDLING
SUBTOTAL
SURCHARGE
TAX
TOTAL
TOTAL_CREDITS
TOTAL_DEALER_OPTION_COST
TOTAL_DISCOUNTS
TOTAL_FEES
TOTAL_FREIGHT
TOTAL_OPTION_MSRP
TOTAL_REBATES
TOTAL_REWARDS
TOTAL_SHIPPING
TOTAL_TAXES
UNIT
}
class ProductStateTypes #FAFF91 {
ARCHIVED
CERTIFIED
COMPANY_OWNED
CUSTOMER_OWNED
DEMO
DISCONTINUED
IN_TRANSIT
NEW
PARTNER_OWNED
REFURBISHED
RENTAL
THIRD_PARTY_OWNED
UNKNOWN
USED
}
class ResourceTypes #FAFF91 {
ACCESSORIES
ACCOUNT
ACTIVITY
ADDRESS
APPLICANT
APPOINTMENT
BILL_ADDRESS
BILL_CONTACT
COMM_CHANNEL
CUSTOMER
DEAL
DEALERSHIP
DEALER_STAFF
DISCOUNT
DRIVER
EXPENSE
FEE
FINANCE
FUNCTION
INCENTIVE
INCIDENT
INSURANCE
INVOICE
LEAD
LINEITEM
MANUFACTURER
OPPORTUNITY
OTHER
PART
PARTY
PART_INVOICE
PROCESS
PRODUCT
PURCHASE_ORDER
RENTAL
SERVICE
SERVICE_INVOICE
SUBSCRIPTION
SYSTEM
TAX
TRADE_IN
VEHICLE
VEHICLE_INVOICE
VEHICLE_OPTION
VENDOR
WARRANTY
WORKFLOW
}
class ServiceLevelTypes #FAFF91 {
EMERGENCY
EXPEDITED
OVERNIGHT
SAME_DAY
STANDARD
}
class ShipmentStateTypes #FAFF91 {
ACTIVE
DELIVERED
LOST_IN_TRANSIT
OPEN
RETURNED_TO_WAREHOUSE
TRACKED
}
class ShippingMethodTypes #FAFF91 {
AIR_FREIGHT
CURBSIDE_PICKUP
DOWNLOAD
ECONOMY
ECO_FRIENDLY
EXPRESS
FLAT_RATE
FREE_SHIPPING
FREIGHT
GROUND
HAZMAT
HYBRID_SHIPPING
INTERNATIONAL_EXPEDITED
INTERNATIONAL_STANDARD
LOCAL_DELIVERY
LOCKER_DELIVERY
OCEAN_FREIGHT
OVERNIGHT
PALLET_DELIVERY
PICKUP
RAIL_FREIGHT
SAME_DAY
TABLE_RATE
TEMPERATURE_CONTROLLED
THREE_DAY_SELECT
TWO_DAY_AIR
}
class TaxTypes #FAFF91 {
EXCISE
OTHER
REGISTRATION
SALES
TOTAL
USE
VALOREM
}
class TimeslotDirectiveTypes #FAFF91 {
AFTER
ANYTIME
BEFORE
BETWEEN
BLOCK
EXACT
FLEXIBLE
OTHER
PREFERRED
REQUIRED
RESTRICTED
UNKNOWN
}
class TransportMethodTypes #FAFF91 {
AIR
COURIER
FREIGHT
GROUND
ROUTE_TRUCK
}
class UnitOfMeasureTypes #FAFF91 {
AMPERE
BI_WEEKS
BYTES
CELSIUS
CITY
COUNTRY
COUNTY
CURRENCY
CUSTOM
DATE
DATE_TIME
DAYS
DAY_OF_MONTH
DISTRICT
DURATION
FAHRENHEIT
FATHOM
FEDERAL
FEET
GALLON
HOURS
INCH
ITEM
KELVIN
KG
KM
KWH
LB
LITER
LOCALITY
METER
MILES
MINUTES
MONTHS
MULTI_YEARS
NA
NAUTICAL
NONE
OCCURRENCE
OTHER
OZ
PERCENT
POINTS
POSTAL
QUARTERS
RANKINE
SEMI_MONTHS
SEMI_YEARS
STATE
STREET
SUB_ADMIN_AREA
SUB_LOCALITY
UNIT
UNKNOWN
UNLIMITED
VOLT
WATT
WEEKS
YARD
YEARS
}
class UomQuantityCategoryTypes #FAFF91 {
COUNT
DEFAULT_LEAD_TIME
DIMENSIONAL_WEIGHT
DIMENSIONS
DIMENSION_UNIT
ELECTRICAL_RATING
EXPIRATION_DATE
GROSS_VOLUME
GROSS_WEIGHT
MATERIAL
MAX_HEIGHT
MAX_LEAD_TIME
MAX_LENGTH
MAX_ORDER_QUANTITY
MAX_WEIGHT
MAX_WIDTH
MIN_HEIGHT
MIN_LENGTH
MIN_ORDER_AVAILABLE
MIN_ORDER_QUANTITY
MIN_PAYMENT_AMOUNT
MIN_PAYMENT_PERCENT
MIN_WEIGHT
MIN_WIDTH
NET_VOLUME
NET_WEIGHT
PACKAGE_QUANTITY
SHELF_LIFE_HOURS
SHIPPING_DIM_GROSS_WEIGHT
SHIPPING_DIM_HEIGHT
SHIPPING_DIM_LENGTH
SHIPPING_DIM_NET_WEIGHT
SHIPPING_DIM_WIDTH
SHIPPING_WEIGHT
TIME
VOLUME
WEIGHT
}
class VehicleInvoiceItemTypes #FAFF91 {
ADJUSTMENT
BASE_VEHICLE
DEALER_ACCESSORY
DESTINATION_CHARGE
DISCOUNT
EQUIPMENT_GROUP
EXTERIOR_COLOR
FACTORY_ACCESSORY
FACTORY_OPTION
FREIGHT_CHARGE
FUEL_CHARGE
HOLD_BACK
INCENTIVE
INTERIOR_COLOR
LOT_MANAGEMENT_CHARGE
MODEL_YEAR
OPTIONAL_EQUIPMENT
OTHER
PACKAGE
PLAN_PRICE
PORT_ACCESSORY
POWERTRAIN
REBATE
STANDARD_EQUIPMENT
SUBSCRIPTION_SERVICE
TOTAL
TOTAL_OPTIONS
TOTAL_VEHICLE_OPTIONS
}
ActorReference -- FinancialEvent
ActorTypes -- ActorReference
AddressReference -- DeliveryProfile
AddressReference -- FulfillmentProfile
AddressReference -- ShipmentProfile
AddressReference *-- PartyReference
AddressTypes *-- AddressReference
AuthorizationLevel *-- CommunicationChannel
CommunicationChannelTypes -- CommunicationChannel
CommunicationChannel *-- PartyReference
ControlAccountReference -- FinancialEvent
ControlAccountReference -- FinancialSplit
ControlAccountReference -- VehicleInvoice
CreditReference *-- FinancialSplit
CurrencyExchange -- Money
DayOfWeekTypes -- TimeSlot
DeliveryDestinationTypes -- DeliveryProfile
DeliveryDestinationTypes -- FulfillmentProfile
DeliveryProfile -- ShipmentProfile
DepositTypes -- FinancialEvent
DiscountMetricValue *-- DiscountReference
DiscountReference *-- FinancialSplit
DurationUomTypes -- EffectivePeriod
EffectivePeriod -- DeliveryProfile
EffectivePeriod -- DiscountReference
EffectivePeriod -- FulfillmentProfile
EffectivePeriod -- Price
EffectivePeriod -- RebateReference
EffectivePeriod -- ShipmentProfile
EffectivePeriod -- ShipmentReference
EffectivePeriod -- TimeSlot
ExceptionSeverityTypes -- TrackingInformation
FeeReference *-- FinancialSplit
FinancialCategoryReference *-- FinancialSplit
FinancialCategoryTypes *-- FinancialEvent
FinancialEventTypes -- FinancialEvent
FinancialEvent *-- VehicleInvoice
FinancialSplit *-- FinancialTrack
FinancialSplit *-- VehicleInvoice
FinancialSplit *-- VehicleInvoiceItem
FinancialTrack *-- VehicleInvoice
FinancialTransactionTypes -- FinancialSplit
FleetReference -- ShipmentProfile
FulfillmentMethodTypes -- DeliveryProfile
FulfillmentMethodTypes -- FulfillmentProfile
FulfillmentProfile -- VehicleInvoice
FulfillmentProfile -- VehicleInvoiceItem
FulfillmentStatusTypes -- FulfillmentProfile
GeneralAmount -- FinancialEvent
GeneralAmount -- FinancialSplit
GeneralAmount -- Money
GeneralAmount -- TaxSplit
IncentiveTypes -- RebateReference
InvoiceReference *-- ShipmentProfile
InvoiceStatusTypes -- VehicleInvoice
InvoiceTypes -- InvoiceReference
InvoiceTypes -- VehicleInvoice
LedgerActionTypes -- FinancialEvent
LedgerActionTypes -- FinancialSplit
Locale -- CommunicationChannel
MetricValue -- ShipmentManifestLine
MetricValue -- ShipmentProfile
MetricValue -- VehicleOption
Money -- Price
NarrativeUomTypes -- MetricValue
OptionDescription *-- VehicleOption
OptionInstallationTypes -- VehicleOption
OptionTypes -- VehicleOption
OrderCategoryTypes *-- DiscountReference
OrderCategoryTypes -- RebateReference
OrderTypes *-- FulfillmentProfile
PartConditionTypes -- ShipmentManifestLine
PartIdentifierReference -- ShipmentManifestLine
PartInvoiceItemTypes -- PartIdentifierReference
PartyReference -- DeliveryProfile
PartyReference -- FulfillmentProfile
PartyReference -- ShipmentProfile
PartyReference -- ShipmentReference
PartyReference -- VehicleInvoice
PartyReference *-- FinancialSplit
PartyReference *-- ShipmentProfile
PartyReference *-- VehicleInvoice
PartyRelationshipTypes *-- PartyReference
PartyTypes *-- FleetReference
PartyTypes -- PartyReference
PartyTypes -- StatusTransitionEvent
PayTypes -- FinancialSplit
PayTypes -- Price
PaymentMethodTypes -- FinancialEvent
PaymentStatusTypes -- VehicleInvoice
PaymentTransactionStatusTypes *-- FinancialEvent
PaymentTypes *-- RebateReference
PersonName -- PartyReference
Position -- ShipmentEvent
Position -- TrackingInformation
Price -- DiscountReference
Price -- RebateReference
Price -- VehicleInvoiceItem
Price -- VehicleOption
PriceTypes *-- Price
ProductPriceItemTypes -- FinancialSplit
ProductPriceItemTypes -- VehicleInvoiceItem
ProductStateTypes *-- DiscountReference
ProductStateTypes -- RebateReference
RebateReference *-- FinancialSplit
ResourceTypes -- FinancialEvent
ResourceTypes -- StatusTransitionEvent
RewardReference *-- FinancialSplit
ServiceLevelTypes -- DeliveryProfile
ServiceLevelTypes -- FulfillmentProfile
ServiceLevelTypes -- ShipmentProfile
ServiceLevelTypes -- ShipmentReference
ShipmentEvent *-- ShipmentProfile
ShipmentEvent *-- TrackingInformation
ShipmentManifestLine *-- ShipmentProfile
ShipmentProfile *-- FulfillmentProfile
ShipmentReference *-- VehicleInvoiceItem
ShipmentStateTypes -- DeliveryProfile
ShipmentStateTypes -- ShipmentEvent
ShipmentStateTypes -- ShipmentProfile
ShipmentStateTypes -- ShipmentReference
ShipmentStateTypes -- TrackingInformation
ShippingMethodTypes *-- DeliveryProfile
ShippingMethodTypes *-- ShipmentProfile
StatusTransitionEvent *-- VehicleInvoice
TaxSplit *-- FinancialSplit
TaxTypes -- TaxSplit
TimeSlot *-- CommunicationChannel
TimeslotDirectiveTypes *-- TimeSlot
TrackingInformation *-- ShipmentProfile
TransportMethodTypes *-- ShipmentProfile
UnitOfMeasure -- ShipmentManifestLine
UnitOfMeasureTypes -- DiscountMetricValue
UnitOfMeasure *-- ShipmentReference
UomQuantityCategoryTypes -- UnitOfMeasure
VehicleInvoiceItemTypes -- VehicleInvoiceItem
VehicleInvoiceItem *-- VehicleInvoice
VehicleOption *-- VehicleInvoiceItem
VehicleReference -- ShipmentProfile
VehicleReference -- VehicleInvoiceItem
VehicleReference *-- VehicleInvoice
@enduml
